LRQA-72932 Add test to assert deactivated users are not counted in roles | master
Sharryxue/liferay-portal pull request #333
Opened 2022-03-02 22:39 UTC by epark18

https://issues.liferay.com/browse/LRQA-72932

2022-03-02 22:39 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-03-02 22:39 UTC, epark18 commented
ci:test:sf

2022-03-02 22:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/1719/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/1719/jenkins-report.html">here</a>.</b></p>

2022-03-02 22:43 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f2993c6f5073b9c63f15c5bede0f17f940580920">f2993c6f5073b9c63f15c5bede0f17f940580920</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/epark18/liferay-portal/tree/LRQA-72932">LRQA-72932</a><br/>Branch GIT ID: <a href="https://github.com/epark18/liferay-portal/commit/a02d63bfc2ca94b02d6c264a249b7523f9688796">a02d63bfc2ca94b02d6c264a249b7523f9688796</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/1719/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/1719/jenkins-report.html">here</a>.</h5></details></html>

2022-03-02 22:50 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/1719/">test-portal-source-format#1719</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/1719/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/333">Sharryxue#333</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1624144188">[master] ci:test:sf - epark18 &gt; Sharryxue - PR#333 - 2022-03-02[14:40:07]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/5912/">publish-testray-report#5912</a><br/></div></div>

2022-03-07 03:12 UTC, Sharryxue requested changes
Hello @epark18,
Please update the test based on feedback, thanks so much.

2022-03-07 03:12 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/rolesandpermissions/cproles/RolesAdmin.testcase
> +	test DeactivatedUsersAreNotCountedInRoles {
This is a test only didactive one user actually, and it's a test for site role, let's rename the test and update the description.

2022-03-07 03:12 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/rolesandpermissions/cproles/RolesAdmin.testcase
> +		}
Since the steps is repeatable, we can using a for loop here, and combine the Given.

2022-03-07 03:12 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/rolesandpermissions/cproles/RolesAdmin.testcase
> +		task ("Then that user should no longer be counted in Roles and no longer be listed as a member or the site") {
The description for Then, "a member or the site" I believe the "**or**" should be "of" here, right? Pay attention to the singular and plural.

2022-03-08 11:42 UTC, Sharryxue requested changes
Hello @epark18,
Let's try to combine the for loops. Thanks

2022-03-08 11:42 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/rolesandpermissions/cproles/RolesAdmin.testcase
> +			}
Hello @epark18,
We can find a way to combine all the for loop here, or at least the rest steps after add sites since the variable is the same.

2022-03-08 11:42 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/rolesandpermissions/cproles/RolesAdmin.testcase
> +			AssertElementNotPresent(
Would you please double check if this step can be replaced by an exist macro? Like the `LexiconEntry.viewNoEntry` or `LexiconTable.viewTableEntryNotPresent`. Thanks

2022-03-08 22:43 UTC, epark18 commented
ci:test:sf

2022-03-08 22:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/1597/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/1597/jenkins-report.html">here</a>.</b></p>

2022-03-08 22:47 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/02bec99471ed706b691c92be479a34335a56614d">02bec99471ed706b691c92be479a34335a56614d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/epark18/liferay-portal/tree/LRQA-72932">LRQA-72932</a><br/>Branch GIT ID: <a href="https://github.com/epark18/liferay-portal/commit/978d7b410b1b5cc49056b271acae04a8eb5f3455">978d7b410b1b5cc49056b271acae04a8eb5f3455</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/1597/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/1597/jenkins-report.html">here</a>.</h5></details></html>

2022-03-08 22:50 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/1597/">test-portal-source-format#1597</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/1597/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/333">Sharryxue#333</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1629634424">[master] ci:test:sf - epark18 &gt; Sharryxue - PR#333 - 2022-03-08[14:44:09]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/5827/">publish-testray-report#5827</a><br/></div></div>

2022-03-09 02:48 UTC, Sharryxue commented
ci:forward

2022-03-09 02:48 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-03-09 02:48 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2022-03-09 02:49 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-26.liferay.com/job/forward-pullrequest/283//consoleFull)

2022-03-09 02:49 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/114351
[Console](https://test-1-26.liferay.com/job/forward-pullrequest/283//consoleFull)

2022-03-09 02:49 UTC, closed without merging

2022-03-09 02:51 UTC, Sharryxue commented
Thanks @epark18,
No changes needed.