LRQA-66114, LRQA-66115, LRQA-66116| master
Sharryxue/liferay-portal pull request #338
Opened 2022-03-09 06:24 UTC by melodywu

https://issues.liferay.com/browse/LRQA-66114

2022-03-09 06:24 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-03-09 06:27 UTC, melodywu commented
ci:test:sf

2022-03-09 06:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/488/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/488/jenkins-report.html">here</a>.</b></p>

2022-03-09 06:34 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/02bec99471ed706b691c92be479a34335a56614d">02bec99471ed706b691c92be479a34335a56614d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-66115">master-qa-66115</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/2c97234c9a6ecfbae268032344403e7c4f0b83dc">2c97234c9a6ecfbae268032344403e7c4f0b83dc</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/488/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/488/jenkins-report.html">here</a>.</h5></details></html>

2022-03-09 06:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/488/">test-portal-source-format#488</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/488/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/338">Sharryxue#338</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1629815456">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#338 - 2022-03-08[22:31:12]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/2007/">publish-testray-report#2007</a><br/></div></div>

2022-03-11 02:53 UTC, melodywu commented
ci:test:sf

2022-03-11 02:53 UTC, melodywu commented
ci:test

2022-03-11 02:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>default</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/826/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/826/jenkins-report.html">here</a>.</b></p>

2022-03-11 02:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/520/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/520/jenkins-report.html">here</a>.</b></p>

2022-03-11 02:55 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5c6fc6bb652140e6f5e417d14b994400e8db3e53">5c6fc6bb652140e6f5e417d14b994400e8db3e53</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-66115">master-qa-66115</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/f49f4d5d5b9b646f5157af78b3eb92e7c1404a02">f49f4d5d5b9b646f5157af78b3eb92e7c1404a02</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/520/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/520/jenkins-report.html">here</a>.</h5></details></html>

2022-03-11 02:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/520/">test-portal-source-format#520</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/520/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/338">Sharryxue#338</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1632240197">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#338 - 2022-03-10[18:53:16]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/2133/">publish-testray-report#2133</a><br/></div></div>

2022-03-11 02:57 UTC, melodywu commented
ci:test:bundle

2022-03-11 02:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>bundle</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/2171/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2171/jenkins-report.html">here</a>.</b></p>

2022-03-11 03:37 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:bundle - 0 out of 1 jobs passed in 39 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5c6fc6bb652140e6f5e417d14b994400e8db3e53">5c6fc6bb652140e6f5e417d14b994400e8db3e53</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4dbd5e4e15ea41326bd5a809d4570e6f0b395ea2">4dbd5e4e15ea41326bd5a809d4570e6f0b395ea2</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3016">Acceptance Upstream DXP (master) #3016</a></p><details><summary><strong>ci:test:bundle - 0 out of 1 jobs PASSED</strong></summary></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2171/jenkins-report.html">here</a>.</h5></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-27/jobs/test-portal-acceptance-pullrequest(master)/builds/2171/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-27/jobs/test-portal-acceptance-pullrequest(master)/builds/2171/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-27/jobs/test-portal-acceptance-pullrequest(master)/builds/2171/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2022-03-11 03:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/2171/">test-portal-acceptance-pullrequest(master)#2171</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2171/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>bundle<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/338">Sharryxue#338</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/6207/">publish-testray-report#6207</a><br/></div></div>

2022-03-11 07:56 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:default - 0 out of 2 jobs passed in 5 hours 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5c6fc6bb652140e6f5e417d14b994400e8db3e53">5c6fc6bb652140e6f5e417d14b994400e8db3e53</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5c6fc6bb652140e6f5e417d14b994400e8db3e53">5c6fc6bb652140e6f5e417d14b994400e8db3e53</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3017">Acceptance Upstream DXP (master) #3017</a></p><details><summary><strong>ci:test:default - 0 out of 2 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/826/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/372539/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/826/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/372539/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>1 Test Passed.<br/>3 Tests Failed.</p></div><ol><li><div><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/372539//consoleText">AXIS_VARIABLE=0 #372539</a><ol><li><div><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/372539//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_AppManagement_FilterMarketplaceStoreApps_">LocalFile.AppManagement#FilterMarketplaceStoreApps</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/826/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.AppManagement_FilterMarketplaceStoreApps/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/826/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.AppManagement_FilterMarketplaceStoreApps/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/826/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/372539//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_AppManagement_SearchMarketplaceStore_">LocalFile.AppManagement#SearchMarketplaceStore</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/826/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.AppManagement_SearchMarketplaceStore/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/826/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.AppManagement_SearchMarketplaceStore/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/826/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/372539//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_AppManagement_ViewPurchasedApp_">LocalFile.AppManagement#ViewPurchasedApp</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/826/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.AppManagement_ViewPurchasedApp/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/826/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.AppManagement_ViewPurchasedApp/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/826/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2022-03-11 07:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/826/">test-portal-acceptance-pullrequest(master)#826</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/826/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>default<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/338">Sharryxue#338</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1632333835">[master] ci:test:default - melodywu &gt; Sharryxue - PR#338 - 2022-03-10[18:53:41]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/2138/">publish-testray-report#2138</a><br/></div></div>

2022-03-14 08:39 UTC, Sharryxue requested changes
Hello @melodywu,
Please update the tests based on the feedbacks.
You can commit only one test at a time to make it easier for both update and review, thanks.

2022-03-14 08:39 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/userbar/UserBar.path
> +	<td>//span[contains(@class,'sign-in')]/a/span | //a[contains(@class,'btn-secondary')]/span</td>
This is a button more specific for marketplace, we'd better add it to its own path file if there is no exist locator to use.

2022-03-14 08:39 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/paths/pathlib/uielements/Button.path
> +	<td>//*[@data-qa-id='searchButton'] | //button[contains(.,'Search')] | //input[contains(@value,'Search')]</td>
This is duplicate with the one added in AppManager.path file, since the search page is specific to marketplace, it's better to add in its own path file.

2022-03-14 08:39 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/marketplace/AppManager.path
> +	<td>//*[@data-qa-id='searchButton'] | //button[contains(.,'Search')] | //input[contains(@value,'Search')]</td>
Leave the only one works for marketplace is enough for our tests.

2022-03-14 08:39 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/paths/pathlib/uielements/TextInput.path
> +	<td>//div[label[contains(.,'${key_text}')]]//input[not(contains(@type,'checkbox'))] | //div[contains(@data-se,'o-form-label') and contains(.,'${key_text}')]//following-sibling::div[contains(@class,'
Instead of edit the exist one, add the locator to AppManager.path if there is no available locator since the page is specific to marketplace.

2022-03-14 08:39 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/controlpanel/apps/appmanager/AppManagement.testcase
> +			WaitForPageLoad();
WaitForPageLoad(); we can put this step in the macro AppManager.loginMarketplaceStore, since it's more related.

2022-03-14 08:39 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/controlpanel/apps/appmanager/AppManagement.testcase
> +				filterName = "Price");
Add assert steps after each filter steps to make sure the filter works as expected.

2022-03-14 08:39 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/controlpanel/apps/appmanager/AppManagement.testcase
> +		task ("When login marketplace store") {
This is more like a Given condition. The whole tests is more like following, update all the 3 tests based on this, thanks e.g.:
```
Give user login marketplace
When user filter by Price
Then the result filter by price
```

2022-03-14 08:39 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/controlpanel/apps/appmanager/AppManagement.testcase
> +	@description = "This test assert that there are Categories, Liferay Version, Price filters in marketplace store."
The test is actually checking the filter works as expected, would you please update the description, thanks.

2022-03-14 08:39 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/controlpanel/apps/appmanager/AppManagement.testcase
> +			AssertElementPresent(locator1 = "AppManager#APP_RESULT_BOX");
If this is a required step to confirm the user login marketplace successfully, we 'd better move it to `loginMarketplaceStore` macro as well.

2022-03-14 08:39 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/controlpanel/apps/appmanager/AppManagement.testcase
> +		task ("When login marketplace store and check user logged") {
`check user logged` would you please complete the description? Like what we are checking here, the user login or logout?

2022-03-14 08:39 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/controlpanel/apps/appmanager/AppManagement.testcase
> +			AssertElementPresent(
Seems this can be covered in task ("Then logout marketplace store"), would you please double check? Thanks.

2022-03-14 08:39 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/controlpanel/apps/appmanager/AppManagement.testcase
> +			AssertElementPresent(
Since these 2 steps are reused in your tests, we can add a new macro to reuse it.

2022-03-14 08:39 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/marketplace/AppManager.path
> +	<td>//span[contains(@class,'aui-field-content')]/label[contains(.,'${key_filterName}')]//following-sibling::span[contains(@class,'aui-field-element')]/select/option[contains(.,'${key_filterBy}')]</t
After checking the page, since the selected value like Free/Paid both show in the page source, locator like this can not confirm it is the selected value. The key value here is selected, please update the locator based on this, thanks.

2022-03-14 08:39 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/marketplace/AppManager.path
> +	<td>//span[contains(@class,'aui-field-content')]/label[contains(.,'${key_filterName}')]//following-sibling::span[contains(@class,'aui-field-element')]/select</td>
It's not friendly for a new user to see such a long locator, it's would be better to make it easier to read and understand.

2022-03-14 08:39 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/marketplace/AppManager.path
> +	<td>//div[contains(@class,'card user')]/div[contains(.,' For Personal Use Only ')]//following-sibling::div[contains(@class,'card-action')]/a[contains(.,'Select')]</td>
1. The path with a bad readable
2. the locator seems for a select button/link, the locator name seems is a user, they're not match properly.
3. Search the general locator first, since the select button is widely used in portal, it probably already exist in other path file.

2022-03-14 08:39 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/marketplace/AppManager.path
> +	<td>//div[contains(@class,'container')]/h3[contains(.,' Thank You! ')]</td>
Duplicate locator, you can search the exist one by h3

2022-03-14 08:39 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/marketplace/AppManager.path
> +	<td>//tr[contains(@class,'portlet-section-body')]//div[contains(@class,'app-entry-display')]//a[contains(.,'${key_searchName}')]</td>
This locator only works for the fist entry. Update it more flexible.
The APP_TITLE and APP_TITLE_1 more like can be combined, search whether there is an exist locator can be reused for title first.

2022-03-14 08:39 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/marketplace/AppManager.path
> +	<td>//div[contains(@class,'button-container')]//a[contains(.,'See Purchased')]</td>
Duplicate, search and use the general one.

2022-03-14 08:39 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/paths/pathlib/uielements/Button.path
> +	<td>//button[contains(.,'Sign In')] | //button[contains(.,'Acceder')] | //button[contains(.,'Anmelden')] | //button[contains(.,'ログイン')] | //button[contains(.,'登录')] | //div[contains(@class,'o-form-b
Duplicate, find and use the exist one, thanks.

2022-03-14 08:39 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/controlpanel/apps/appmanager/AppManagement.testcase
> +	test ViewPurchasedApp {
Should this test see the purchased App via Control Panel > MARKETPLACE
 > Purchased, would you please double check, thanks.

2022-03-15 01:33 UTC, melodywu commented
> Hello @melodywu, Please update the tests based on the feedbacks. You can commit only one test at a time to make it easier for both update and review, thanks.

OK

2022-03-15 01:35 UTC, closed without merging