LRQA-73952 | master
Sharryxue/liferay-portal pull request #348
Opened 2022-03-23 03:21 UTC by melodywu

https://issues.liferay.com/browse/LRQA-73952

2022-03-23 03:21 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-03-23 03:22 UTC, melodywu commented
ci:test:sf

2022-03-23 03:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/695/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/695/jenkins-report.html">here</a>.</b></p>

2022-03-23 03:26 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6f8578c445a12e8539c3c26030f0f5961ba6048f">6f8578c445a12e8539c3c26030f0f5961ba6048f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-73952">master-qa-73952</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/bd29acba7684eb2b419f8766c191b9ed4c94fcd4">bd29acba7684eb2b419f8766c191b9ed4c94fcd4</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/695/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/695/jenkins-report.html">here</a>.</h5></details></html>

2022-03-23 03:28 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/695/">test-portal-source-format#695</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/695/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/348">Sharryxue#348</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1643708602">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#348 - 2022-03-22[20:22:49]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/2810/">publish-testray-report#2810</a><br/></div></div>

2022-03-23 07:48 UTC, Sharryxue commented
Just starting review.

2022-03-23 07:53 UTC, Sharryxue requested changes
Please update the tests, thanks

2022-03-23 07:53 UTC, Sharryxue commented on modules/apps/account/account-test/src/testFunctional/tests/2BAccount.testcase
> +		Accounts.addOwnedAccountRole(accountRoleTitle = "Account Specific Role");
Not adding the role in set-up since it's not a common step for all tests in the test file.

2022-03-24 06:23 UTC, melodywu commented
ci:test:sf

2022-03-24 06:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-source-format/968/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/968/jenkins-report.html">here</a>.</b></p>

2022-03-24 06:28 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/563c772eb6d9e4383542834309d89899495cbe7a">563c772eb6d9e4383542834309d89899495cbe7a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-73952">master-qa-73952</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/e01fe508f6f4a5bed89b1827a00e6aa5b69c9fc4">e01fe508f6f4a5bed89b1827a00e6aa5b69c9fc4</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-source-format/968/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/968/jenkins-report.html">here</a>.</h5></details></html>

2022-03-24 06:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-source-format/968/">test-portal-source-format#968</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/968/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/348">Sharryxue#348</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1645316446">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#348 - 2022-03-23[23:24:05]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/3770/">publish-testray-report#3770</a><br/></div></div>

2022-03-25 09:38 UTC, Sharryxue commented
Just starting review.

2022-03-25 09:39 UTC, Sharryxue commented
No more changes needed. Thanks for fixing the issue @melodywu

2022-03-25 09:55 UTC, Sharryxue commented
Rebase and resend [Sharryxue/liferay-portal#352](https://github.com/Sharryxue/liferay-portal/pull/352).

2022-03-25 09:55 UTC, closed without merging