LRQA-73951 | master
Sharryxue/liferay-portal pull request #349
Opened 2022-03-23 04:44 UTC by melodywu

https://issues.liferay.com/browse/LRQA-73951

2022-03-23 04:44 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-03-23 04:45 UTC, melodywu commented
ci:test

2022-03-23 04:45 UTC, melodywu commented
ci:test:sf

2022-03-23 04:47 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/2513/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/2513/jenkins-report.html">here</a>.</b></p>

2022-03-23 04:49 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6f8578c445a12e8539c3c26030f0f5961ba6048f">6f8578c445a12e8539c3c26030f0f5961ba6048f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-73951">master-qa-73951</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/54574bad843adc2ede4557103f53c12fe78a05cc">54574bad843adc2ede4557103f53c12fe78a05cc</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/2513/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/2513/jenkins-report.html">here</a>.</h5></details></html>

2022-03-23 05:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/2513/">test-portal-source-format#2513</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/2513/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/349">Sharryxue#349</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1643753042">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#349 - 2022-03-22[21:46:13]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/9158/">publish-testray-report#9158</a><br/></div></div>

2022-03-23 05:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>default</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/3109/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3109/jenkins-report.html">here</a>.</b></p>

2022-03-23 07:55 UTC, melodywu commented
ci:test:bundle

2022-03-23 08:08 UTC, Sharryxue commented
Just starting review.

2022-03-23 08:09 UTC, Sharryxue requested changes
Need changes, thanks.

2022-03-23 08:09 UTC, Sharryxue commented on modules/apps/account/account-test/src/testFunctional/tests/Accounts.testcase
> +		for (var accountRoleName : list "Account Role 4") {
No need to use loop here.

2022-03-23 08:09 UTC, Sharryxue commented on modules/apps/account/account-test/src/testFunctional/tests/Accounts.testcase
> +		for (var accountRoleName : list "Account Role 4") {
same here.

2022-03-23 08:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>bundle</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/1145/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1145/jenkins-report.html">here</a>.</b></p>

2022-03-23 09:16 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:bundle - 0 out of 1 jobs passed in 32 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6f8578c445a12e8539c3c26030f0f5961ba6048f">6f8578c445a12e8539c3c26030f0f5961ba6048f</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6f8578c445a12e8539c3c26030f0f5961ba6048f">6f8578c445a12e8539c3c26030f0f5961ba6048f</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3056">Acceptance Upstream DXP (master) #3056</a></p><details><summary><strong>ci:test:bundle - 0 out of 1 jobs PASSED</strong></summary></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1145/jenkins-report.html">here</a>.</h5></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-37/jobs/test-portal-acceptance-pullrequest(master)/builds/1145/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-37/jobs/test-portal-acceptance-pullrequest(master)/builds/1145/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-37/jobs/test-portal-acceptance-pullrequest(master)/builds/1145/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2022-03-23 09:18 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/1145/">test-portal-acceptance-pullrequest(master)#1145</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1145/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>bundle<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/349">Sharryxue#349</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/2851/">publish-testray-report#2851</a><br/></div></div>

2022-03-23 09:22 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:default - 0 out of 2 jobs passed in 4 hours 19 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6f8578c445a12e8539c3c26030f0f5961ba6048f">6f8578c445a12e8539c3c26030f0f5961ba6048f</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6f8578c445a12e8539c3c26030f0f5961ba6048f">6f8578c445a12e8539c3c26030f0f5961ba6048f</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3056">Acceptance Upstream DXP (master) #3056</a></p><details><summary><strong>ci:test:default - 0 out of 2 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/3109/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/492202/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3109/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/492202/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>1 Test Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/492202//consoleText">AXIS_VARIABLE=0 #492202</a><ol><li><div><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/492202//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Accounts_CanChangePaginationInRolesList_">LocalFile.Accounts#CanChangePaginationInRolesList</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-32/test-portal-acceptance-pullrequest(master)/3109/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.Accounts_CanChangePaginationInRolesList/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-32/test-portal-acceptance-pullrequest(master)/3109/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.Accounts_CanChangePaginationInRolesList/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-03/test-1-32/test-portal-acceptance-pullrequest(master)/3109/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2022-03-23 09:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/3109/">test-portal-acceptance-pullrequest(master)#3109</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3109/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>default<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/349">Sharryxue#349</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1643914436">[master] ci:test:default - melodywu &gt; Sharryxue - PR#349 - 2022-03-22[22:03:53]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/9165/">publish-testray-report#9165</a><br/></div></div>

2022-03-24 06:40 UTC, melodywu commented
ci:test:sf

2022-03-24 06:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/1939/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/1939/jenkins-report.html">here</a>.</b></p>

2022-03-24 06:43 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/563c772eb6d9e4383542834309d89899495cbe7a">563c772eb6d9e4383542834309d89899495cbe7a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-73951">master-qa-73951</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/80d550d515dc12803a17ab00421d50b2938f9bb7">80d550d515dc12803a17ab00421d50b2938f9bb7</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/1939/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/1939/jenkins-report.html">here</a>.</h5></details></html>

2022-03-24 06:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/1939/">test-portal-source-format#1939</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/1939/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/349">Sharryxue#349</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1645332367">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#349 - 2022-03-23[23:40:45]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/6804/">publish-testray-report#6804</a><br/></div></div>

2022-03-25 09:30 UTC, Sharryxue commented
Just starting review.

2022-03-25 09:39 UTC, Sharryxue commented
No more changes needed. Thanks for fixing the issue @melodywu

2022-03-25 09:56 UTC, Sharryxue commented
Rebase and resend [Sharryxue/liferay-portal#352](https://github.com/Sharryxue/liferay-portal/pull/352).

2022-03-25 09:56 UTC, closed without merging