master-qa-50753_1
Sharryxue/liferay-portal pull request #357
Opened 2022-03-29 02:59 UTC by chaowang-123

https://issues.liferay.com/browse/LRQA-50753
Submit to master.

2022-03-29 02:59 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-03-29 02:59 UTC, chaowang-123 commented
ci:test:sf

2022-03-29 03:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/2217/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/2217/jenkins-report.html">here</a>.</b></p>

2022-03-29 03:14 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/89ea6114c45e45c60cc945726f5c26108b3e7669">89ea6114c45e45c60cc945726f5c26108b3e7669</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/chaowang-123/liferay-portal/tree/master-qa-50753_1">master-qa-50753_1</a><br/>Branch GIT ID: <a href="https://github.com/chaowang-123/liferay-portal/commit/202bcd3a1b1da284ef6ec5aa6980efb5162624e3">202bcd3a1b1da284ef6ec5aa6980efb5162624e3</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/2217/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/2217/jenkins-report.html">here</a>.</h5></details></html>

2022-03-29 03:17 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/2217/">test-portal-source-format#2217</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/2217/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/357">Sharryxue#357</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1649316552">[master] ci:test:sf - chaowang-123 &gt; Sharryxue - PR#357 - 2022-03-28[20:11:44]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/7961/">publish-testray-report#7961</a><br/></div></div>

2022-03-29 09:26 UTC, Sharryxue commented
Just starting review.

2022-03-29 09:29 UTC, Sharryxue requested changes
Hello @chaowang-123 ,
Thanks for writing the test.
Only one change required. Please use the exist macro in test steps instead of using the function directly. Thanks

2022-03-29 09:29 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/users/gdpr/GDPR.testcase
> +		AssertTextEquals(
Please use the exist macro to replace.

2022-03-30 01:33 UTC, chaowang-123 commented
ci:test:sf

2022-03-30 01:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-15.liferay.com/job/test-portal-source-format/3618/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/3618/jenkins-report.html">here</a>.</b></p>

2022-03-30 01:39 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/074163ce6ee880ceb128dce06cb0f366c0de278f">074163ce6ee880ceb128dce06cb0f366c0de278f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/chaowang-123/liferay-portal/tree/master-qa-50753_1">master-qa-50753_1</a><br/>Branch GIT ID: <a href="https://github.com/chaowang-123/liferay-portal/commit/315d688b460580068ac8d287450333b83d11d384">315d688b460580068ac8d287450333b83d11d384</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-15.liferay.com/job/test-portal-source-format/3618/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/3618/jenkins-report.html">here</a>.</h5></details></html>

2022-03-30 01:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-15.liferay.com/job/test-portal-source-format/3618/">test-portal-source-format#3618</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/3618/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/357">Sharryxue#357</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1650634540">[master] ci:test:sf - chaowang-123 &gt; Sharryxue - PR#357 - 2022-03-29[18:33:20]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-15.liferay.com/job/publish-testray-report/2337/">publish-testray-report#2337</a><br/></div></div>

2022-03-30 12:05 UTC, Sharryxue commented
Just starting review.

2022-03-30 12:24 UTC, Sharryxue commented
No additional changes needed, just squashed the commits.
View [74b50148](https://github.com/Sharryxue/liferay-portal/pull/364/commits/74b50148fc9fd28d597e702838180ab192343047)

2022-03-30 12:24 UTC, closed without merging