master-qa-50756
Sharryxue/liferay-portal pull request #361
Opened 2022-03-30 05:12 UTC by chaowang-123

https://issues.liferay.com/browse/LRQA-50756
Submit to master.

2022-03-30 05:13 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-03-30 05:13 UTC, chaowang-123 commented
ci:test:sf

2022-03-30 05:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/1950/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/1950/jenkins-report.html">here</a>.</b></p>

2022-03-30 05:21 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2f6c3e638afbe31d63af5c62dfe5ed43150cb367">2f6c3e638afbe31d63af5c62dfe5ed43150cb367</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/chaowang-123/liferay-portal/tree/master-qa-50756">master-qa-50756</a><br/>Branch GIT ID: <a href="https://github.com/chaowang-123/liferay-portal/commit/f959dbcb95c7622a86da8367da298d3a4d807401">f959dbcb95c7622a86da8367da298d3a4d807401</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/1950/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/1950/jenkins-report.html">here</a>.</h5></details></html>

2022-03-30 05:24 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/1950/">test-portal-source-format#1950</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/1950/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/361">Sharryxue#361</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1650922033">[master] ci:test:sf - chaowang-123 &gt; Sharryxue - PR#361 - 2022-03-29[22:17:59]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/7182/">publish-testray-report#7182</a><br/></div></div>

2022-03-30 11:53 UTC, Sharryxue commented
Just starting review.

2022-03-30 12:19 UTC, Sharryxue requested changes
Hello @chaowang-123 
Thanks for applying the BDD format, there are some changes required before forwarding it.

Bests

2022-03-30 12:19 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/macros/GDPR.macro
> +	macro anonymizeStagedAndLiveDatainApplicationCP {
rename it to anonymizeTheSpecificEntry

2022-03-30 12:19 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/users/gdpr/GDPR.testcase
> +	test CanAnonymizeASingleStagedAndLiveEntryFromWebContent {
Rename it to CanAnonymizeASingleStagedAndLiveWebContentEntry

2022-03-30 12:19 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/users/gdpr/GDPR.testcase
> +		task ("Given add the staged entry with web content and publish to live this entry") {
We not using multi Given when apply the BDD format, we can either put them in one given block or nested by using And.
In order to put the Given together, we can use a description like this e.g.:Publish the staged web content entries to live as a new admin user.

2022-03-30 12:19 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/users/gdpr/GDPR.testcase
> +		task ("And select anonymize staged 'GDPR Anonymize Article 1' entry and lived 'GDPR Anonymize Article 2' entry") {
If it's hard to combine the When, using And to nested it like following.
task ("When balbalbalbla")
    task ("And balbalbalbla")

2022-03-31 09:47 UTC, Sharryxue commented
Just starting review.

2022-03-31 09:50 UTC, Sharryxue commented
Made following changes.
- Squashed the commits, when we have need update the changes, instead of adding an additional commit, modify the exist commits that have issues.
- Combined the Given task
- Nested the And block into when task
- Shorten the commit message
View [3dc5527%5E...a164e94](https://github.com/Sharryxue/liferay-portal/compare/3dc5527%5E...a164e94)

Resend [Sharryxue/liferay-portal#371](https://github.com/Sharryxue/liferay-portal/pull/371)

2022-04-12 07:51 UTC, closed without merging