master-qa-50751
Sharryxue/liferay-portal pull request #362
Opened 2022-03-30 10:16 UTC by jaydawu

https://issues.liferay.com/browse/LRQA-50751
Submit for master.

2022-03-30 10:16 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-03-30 10:16 UTC, jaydawu commented
ci:test:sf

2022-03-30 10:18 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-17.liferay.com/job/test-portal-source-format/5687/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/5687/jenkins-report.html">here</a>.</b></p>

2022-03-30 10:21 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2f6c3e638afbe31d63af5c62dfe5ed43150cb367">2f6c3e638afbe31d63af5c62dfe5ed43150cb367</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/jaydawu/liferay-portal/tree/master-qa-50751">master-qa-50751</a><br/>Branch GIT ID: <a href="https://github.com/jaydawu/liferay-portal/commit/514bd6ca1b25d154014901c17c71a2999799829b">514bd6ca1b25d154014901c17c71a2999799829b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-17.liferay.com/job/test-portal-source-format/5687/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/5687/jenkins-report.html">here</a>.</h5></details></html>

2022-03-30 10:25 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-17.liferay.com/job/test-portal-source-format/5687/">test-portal-source-format#5687</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/5687/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/362">Sharryxue#362</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1651065540">[master] ci:test:sf - jaydawu &gt; Sharryxue - PR#362 - 2022-03-30[03:17:08]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-17.liferay.com/job/publish-testray-report/2122/">publish-testray-report#2122</a><br/></div></div>

2022-04-07 08:59 UTC, Sharryxue commented
Just starting review.

2022-04-07 08:59 UTC, Sharryxue commented
Just starting review.

2022-04-12 04:13 UTC, Sharryxue requested changes
Hello @jaydawu,
Please update the test to assert the items that has no entries are not clickable in the Export Personal Data page. Thanks.

2022-04-12 04:13 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/users/gdpr/GDPR.testcase
> +			User.exportPersonalDataCP(
Instead of exporting again, view the Export Personal Data page is enough for this test to assert the disabled items with no entries.

2022-04-12 08:51 UTC, jaydawu commented
ci:test:sf

2022-04-12 08:56 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/29509a8830b3e87568bf5c5d3aea0af4a93356d4">29509a8830b3e87568bf5c5d3aea0af4a93356d4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/jaydawu/liferay-portal/tree/master-qa-50751">master-qa-50751</a><br/>Branch GIT ID: <a href="https://github.com/jaydawu/liferay-portal/commit/6fb1dbf71742c3266763ca528e3b746c81386540">6fb1dbf71742c3266763ca528e3b746c81386540</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-17.liferay.com/job/test-portal-source-format/5710/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/5710/jenkins-report.html">here</a>.</h5></details></html>

2022-04-12 08:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-17.liferay.com/job/test-portal-source-format/5710/">test-portal-source-format#5710</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/5710/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/362">Sharryxue#362</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1661603339">[master] ci:test:sf - jaydawu &gt; Sharryxue - PR#362 - 2022-04-12[01:52:05]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-17.liferay.com/job/publish-testray-report/2162/">publish-testray-report#2162</a><br/></div></div>

2022-04-13 03:03 UTC, Sharryxue commented
Just starting review.

2022-05-06 07:54 UTC, brianwulbern commented
https://github.com/Sharryxue/liferay-portal/pull/381

2022-05-06 07:55 UTC, brianwulbern commented
ci:close

2022-05-06 07:55 UTC, closed without merging