master-qa-50759
Sharryxue/liferay-portal pull request #363
Opened 2022-03-30 10:19 UTC by jaydawu

https://issues.liferay.com/browse/LRQA-50759
Submit for master.

2022-03-30 10:19 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-03-30 10:19 UTC, jaydawu commented
ci:test:sf

2022-03-30 10:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-source-format/739/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/739/jenkins-report.html">here</a>.</b></p>

2022-03-30 10:23 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2f6c3e638afbe31d63af5c62dfe5ed43150cb367">2f6c3e638afbe31d63af5c62dfe5ed43150cb367</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/jaydawu/liferay-portal/tree/master-qa-50759">master-qa-50759</a><br/>Branch GIT ID: <a href="https://github.com/jaydawu/liferay-portal/commit/47fba8cebe3de2375e08633ecb68656a0752947b">47fba8cebe3de2375e08633ecb68656a0752947b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-source-format/739/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/739/jenkins-report.html">here</a>.</h5></details></html>

2022-03-30 10:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-source-format/739/">test-portal-source-format#739</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/739/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/363">Sharryxue#363</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1651065554">[master] ci:test:sf - jaydawu &gt; Sharryxue - PR#363 - 2022-03-30[03:19:46]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/3056/">publish-testray-report#3056</a><br/></div></div>

2022-04-07 03:54 UTC, Sharryxue commented
Just starting review.

2022-04-07 05:44 UTC, Sharryxue requested changes
Hello @jaydawu 
Thanks for adding the test, there are some additional changes needed before we merge it, would you please take a look into it? Thanks in advance.

2022-04-07 05:44 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/macros/GDPR.macro
> +		var key_rowEntry = "${rowEntry}";
This is kind of duplicate with macro deleteTheSpecificEntry.

2022-04-07 05:44 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/users/gdpr/GDPR.testcase
> +		task ("And assert entry is deleted from live.") {
Please nested the And into When block. Thanks

2022-04-07 05:44 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/users/gdpr/GDPR.testcase
> +			User.activateCP(
No need to assert the entry as the new user, just assert it as Test Test is OK since both of the users are admin.

2022-04-07 09:38 UTC, jaydawu commented
@Sharryxue Sure, Thank you!

2022-04-07 09:41 UTC, closed without merging

2022-04-07 12:01 UTC, Sharryxue commented
Hello @jaydawu ,
It would be good to add a comment to referring the new pr we opened for the same ticket. Thanks
We can simple comment a message like following.
Resend [Sharryxue/liferay-portal#377](https://github.com/Sharryxue/liferay-portal/pull/377).

2022-04-08 01:31 UTC, jaydawu commented
@Sharryxue Got it, I'll apply it next time, thanks!