LRQA-73903 | Account#RemoveUserFromAccountViaUsersAdmin | master
Sharryxue/liferay-portal pull request #380
Opened 2022-04-12 16:43 UTC by epark18

https://issues.liferay.com/browse/LRQA-73093

2022-04-12 16:43 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-04-12 16:43 UTC, epark18 commented
ci:test:sf

2022-04-12 16:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/1781/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1781/jenkins-report.html">here</a>.</b></p>

2022-04-12 16:47 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3e03bc665911e43653095ffb59c1b94fe5a6d994">3e03bc665911e43653095ffb59c1b94fe5a6d994</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/epark18/liferay-portal/tree/LRQA-73093">LRQA-73093</a><br/>Branch GIT ID: <a href="https://github.com/epark18/liferay-portal/commit/c0cdf1a43347af1dfece29153f6ff444ef7be4bf">c0cdf1a43347af1dfece29153f6ff444ef7be4bf</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1781/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1781/jenkins-report.html">here</a>.</h5></details></html>

2022-04-12 16:49 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1781/">test-portal-source-format#1781</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1781/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/380">Sharryxue#380</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1662010083">[master] ci:test:sf - epark18 &gt; Sharryxue - PR#380 - 2022-04-12[09:44:17]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/6444/">publish-testray-report#6444</a><br/></div></div>

2022-04-13 10:07 UTC, Sharryxue commented
Just starting review.

2022-04-13 11:08 UTC, Sharryxue requested changes
Hello @epark18
Please update the test based on the review feedback. Remember to search and use the existing _locator_ before create a new one, and use the exist _macro_ instead of adding _function_ directly in _test_.

2022-04-13 11:08 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/usersandorganizations/UsersAndOrganizationsEditUser.path
> +	<td>ACCOUNTS_TABLE_REMOVE_ACCOUNT</td>
Please search and use the exist locator instead of creating a new one. Thanks

2022-04-13 11:08 UTC, Sharryxue commented on modules/apps/account/account-test/src/testFunctional/tests/Accounts.testcase
> +				User.assignAccountCP(
We can use the json macro that assign user to account, since the function in User.assignAccountCP is covered in other test already.

2022-04-13 11:08 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/macros/User.macro
> +		Button.clickSave();
We'd better add the view success message step after saving.

2022-04-13 11:08 UTC, Sharryxue commented on modules/apps/account/account-test/src/testFunctional/tests/Accounts.testcase
> +			Refresh();
Since the page would refresh when clicking the Save button, seems the Refresh here is duplicate. Would you please double check? Thanks

2022-04-13 11:08 UTC, Sharryxue commented on modules/apps/account/account-test/src/testFunctional/tests/Accounts.testcase
> +			AssertElementPresent(
This probably can be replace by the existing macro in LexibleTable, would you please double check? Thanks

2022-04-13 11:08 UTC, Sharryxue commented on modules/apps/account/account-test/src/testFunctional/tests/Accounts.testcase
> +			AssertElementNotPresent(
Same as above. Please using the existing macro if possible.

2022-04-14 00:31 UTC, epark18 commented
Thank you for the suggestions! I will close this and resend.

2022-04-14 00:31 UTC, closed without merging