LRQA-73645 | master
Sharryxue/liferay-portal pull request #384
Opened 2022-04-15 06:33 UTC by melodywu

https://issues.liferay.com/browse/LRQA-73645

2022-04-15 06:33 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-04-15 06:34 UTC, melodywu commented
ci:test:sf

2022-04-15 06:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/1970/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/1970/jenkins-report.html">here</a>.</b></p>

2022-04-15 06:37 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/653eafc671c16a53a61c4dd45aee6217350ea417">653eafc671c16a53a61c4dd45aee6217350ea417</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-73645">master-qa-73645</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/410273c0e65e3a01caef9f90c924aaa0ae5dd28f">410273c0e65e3a01caef9f90c924aaa0ae5dd28f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/1970/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/1970/jenkins-report.html">here</a>.</h5></details></html>

2022-04-25 02:29 UTC, Sharryxue commented
Just starting review.

2022-04-25 05:46 UTC, Sharryxue commented on modules/apps/account/account-test/src/testFunctional/macros/AccountGroups.macro
> +	macro unassign {
This should be duplicate with the exist macro, please double check it, thanks.
Always remember to check the exist macro first before create a new one.

2022-04-25 05:47 UTC, Sharryxue requested changes
Hello @melodywu ,
Please use the exist macro instead. Thanks.

2022-04-26 02:14 UTC, melodywu commented
> LRQA-73645 Add testcase to unassign account from group

Done thanks a lot

2022-04-26 02:14 UTC, melodywu commented
ci:test:sf

2022-04-26 02:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/1109/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/1109/jenkins-report.html">here</a>.</b></p>

2022-04-26 02:18 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ddb0c18e73ac5e04258fe51ea82bb29a5eae2c06">ddb0c18e73ac5e04258fe51ea82bb29a5eae2c06</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-73645">master-qa-73645</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/de622883f4d737b269df6b6f9b0d54bdd4e4d2f7">de622883f4d737b269df6b6f9b0d54bdd4e4d2f7</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/1109/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/1109/jenkins-report.html">here</a>.</h5></details></html>

2022-04-26 02:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/1109/">test-portal-source-format#1109</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/1109/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/384">Sharryxue#384</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1703505638">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#384 - 2022-04-25[19:15:12]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/4467/">publish-testray-report#4467</a><br/></div></div>

2022-04-26 03:29 UTC, Sharryxue commented
Just starting review.

2022-04-26 05:59 UTC, Sharryxue commented
No additional changes needed.

2022-04-26 13:35 UTC, Sharryxue commented
Rebased and resend [Sharryxue/liferay-portal#396](https://github.com/Sharryxue/liferay-portal/pull/396).

2022-04-26 13:35 UTC, closed without merging