LRQA-73815 | master
Sharryxue/liferay-portal pull request #394
Opened 2022-04-22 00:52 UTC by Tim-Cao

https://issues.liferay.com/browse/LRQA-73815

This is only for master.

@Sharryxue
@yanan

2022-04-22 00:52 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-04-22 00:52 UTC, Tim-Cao commented
ci:test:sf

2022-04-22 00:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/51/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/51/jenkins-report.html">here</a>.</b></p>

2022-04-22 00:56 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/858079741983cffb213091f895eae9a0a2b0ea2d">858079741983cffb213091f895eae9a0a2b0ea2d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/yanan/liferay-portal/tree/master-qa-73815">master-qa-73815</a><br/>Branch GIT ID: <a href="https://github.com/yanan/liferay-portal/commit/8b7bfcb05ed7ac02ef8a8f2b5de6bd9a74745b30">8b7bfcb05ed7ac02ef8a8f2b5de6bd9a74745b30</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/51/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/51/jenkins-report.html">here</a>.</h5></details></html>

2022-04-22 00:58 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/51/">test-portal-source-format#51</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/51/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/394">Sharryxue#394</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1693873093">[master] ci:test:sf - yanan &gt; Sharryxue - PR#394 - 2022-04-21[17:53:06]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/173/">publish-testray-report#173</a><br/></div></div>

2022-04-27 08:26 UTC, Sharryxue commented
Just starting review.

2022-05-12 07:49 UTC, Sharryxue requested changes
Hello @yanan,
Thanks for adding the test, there are additional changes required before we forward the commit, would you please referring the review feedback to update the test? Thanks in advance.

2022-05-12 07:49 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/rolesandpermissions/usecase/RolesandpermissionsUsecase.testcase
> +	test DefaultSiteRoleShouldNotBeInheritedByGuest {
Rename it to DefaultSiteRoleIsNotInheritedByGuestUser to make the test more clear.

2022-05-12 07:49 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/rolesandpermissions/usecase/RolesandpermissionsUsecase.testcase
> +		task ("Add a new regular Role") {
Not necessary to give description in task for a single step, since the macro can explain itself well.
If you want to practice the BDD modal like Given/When /Then here, we can combine the preconditions in Given, and put the change permission steps in When, put the confirm steps in Then. 
But if you have no confidence in using it(BDD), we can just combining the first two task as one.

2022-05-12 07:49 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/rolesandpermissions/usecase/RolesandpermissionsUsecase.testcase
> +				layoutName = "public widget page");
Rename the page name to "Public Widget Page", first letter in caption.

2022-05-12 07:49 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/rolesandpermissions/usecase/RolesandpermissionsUsecase.testcase
> +		task ("Define permissions on the DM portlet") {
It would be better to indicate what the permission is in description.

2022-05-12 07:49 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/rolesandpermissions/usecase/RolesandpermissionsUsecase.testcase
> +			AssertElementNotPresent(
Use the exist macro instead if possible. Thanks

2022-05-12 07:49 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/rolesandpermissions/usecase/RolesandpermissionsUsecase.testcase
> +		task ("Add a new site and assign it to the regular role") {
Based on the original ticket, the new added regular role is expected to assign to the default site. Would you please double check? Thanks in advance.

2022-05-13 12:39 UTC, yanan commented
Hello @Sharryxue ,
Thanks for the comments, I've force pushed in this pull request since I can't close it, please help review and feel free to let me know if a new pull request is needed. thank you. 
cc @Tim-Cao

2022-05-18 11:08 UTC, Sharryxue commented
Just starting review.

2022-05-18 11:37 UTC, Sharryxue commented
No changes needed.

2022-05-19 07:04 UTC, Sharryxue commented
Rebase and resend [Sharryxue/liferay-portal#406](https://github.com/Sharryxue/liferay-portal/pull/406)

2022-05-19 07:04 UTC, closed without merging