LRQA-73815 | master
Sharryxue/liferay-portal pull request #395
Opened 2022-04-22 01:50 UTC by Tim-Cao

https://issues.liferay.com/browse/LRQA-73815

This is only for master.

@lilylcl
@Sharryxue

2022-04-22 01:50 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-04-22 01:50 UTC, Tim-Cao commented
ci:test:sf

2022-04-22 01:52 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/1080/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/1080/jenkins-report.html">here</a>.</b></p>

2022-04-22 01:53 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/52ec0ec7f44d09228eea714caf30f12e44342254">52ec0ec7f44d09228eea714caf30f12e44342254</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/lilylcl/liferay-portal/tree/LRQA-73815">LRQA-73815</a><br/>Branch GIT ID: <a href="https://github.com/lilylcl/liferay-portal/commit/1cb07cde24d415d0d6f953c6b889115bff519119">1cb07cde24d415d0d6f953c6b889115bff519119</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/1080/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/1080/jenkins-report.html">here</a>.</h5></details></html>

2022-04-22 01:55 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/1080/">test-portal-source-format#1080</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/1080/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/395">Sharryxue#395</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1693926500">[master] ci:test:sf - lilylcl &gt; Sharryxue - PR#395 - 2022-04-21[18:50:44]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/4350/">publish-testray-report#4350</a><br/></div></div>

2022-04-27 09:34 UTC, Sharryxue commented
Just starting review.

2022-05-12 07:47 UTC, Sharryxue requested changes
Hello @lilylcl,
Please referring the review feedback to update the test, thanks in advance.

2022-05-12 07:47 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/rolesandpermissions/usecase/RolesandpermissionsUsecase.testcase
> +	@description = "This is a test for LPS-148855. The test site role shouldn't be inherited by Guest."
The "test site role" in description is not accurate, it can be the default site role.

2022-05-12 07:47 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/rolesandpermissions/usecase/RolesandpermissionsUsecase.testcase
> +	test DefaultSiteRoleShouldNotBeInheritedByGuest {
Rename it to DefaultSiteRoleIsNotInheritedByGuestUser to make the test more clear.

2022-05-12 07:47 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/rolesandpermissions/usecase/RolesandpermissionsUsecase.testcase
> +				groupName = "Site Name",
Should this be the default site?

2022-05-12 07:47 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/rolesandpermissions/usecase/RolesandpermissionsUsecase.testcase
> +		task ("Add a page to a new site") {
When writing test, put the related steps together or be the pre/next task, this way, it can helps others understand the testing steps well.
Like here, we can put the task ("Add a page to a new site") just before task ("Add a Document and Media widget to page and add a new file"), since add the site is for adding DM entry.

2022-05-12 07:47 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/rolesandpermissions/usecase/RolesandpermissionsUsecase.testcase
> +		task ("Add a Document and Media widget to page and add a new file") {
The order in description not match the steps, remember the description is summaries based on the real test steps.

2022-05-12 07:47 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/rolesandpermissions/usecase/RolesandpermissionsUsecase.testcase
> +				layoutName = "test page");
Update the page name using capital for first letter and give it to a meaningful name like DM Page.

2022-05-12 07:47 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/rolesandpermissions/usecase/RolesandpermissionsUsecase.testcase
> +				permissionsKeyList = "CONFIGURATION_PERMISSIONS_VIEW_CHECKBOX",
Is the variable _permissionsKeyList_ necessary?

2022-05-12 07:47 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/rolesandpermissions/usecase/RolesandpermissionsUsecase.testcase
> +				permissionsKeyList = "CONFIGURATION_PERMISSIONS_VIEW_CHECKBOX",
Same issue here.

2022-05-12 07:47 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/rolesandpermissions/usecase/RolesandpermissionsUsecase.testcase
> +			AssertElementPresent(
Would you please double check if this can be replaced by exist macro? Thanks

2022-05-12 07:47 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/rolesandpermissions/usecase/RolesandpermissionsUsecase.testcase
> +			AssertElementNotPresent(
Same as above. Thanks

2022-05-23 08:47 UTC, Sharryxue commented
Closed since the test is merged in another pr.

2022-05-23 08:47 UTC, closed without merging