LRQA-75272 | master
Sharryxue/liferay-portal pull request #414
Opened 2022-05-27 06:39 UTC by melodywu

https://issues.liferay.com/browse/LRQA-75272

2022-05-27 06:39 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-05-27 06:40 UTC, melodywu commented
ci:test:sf

2022-05-27 06:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/88/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/88/jenkins-report.html">here</a>.</b></p>

2022-05-27 06:43 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b86626cae4f0fd87a616c333615e8048ddb1ddfe">b86626cae4f0fd87a616c333615e8048ddb1ddfe</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-75272">master-qa-75272</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/9d366073f58559b41e63fa1d9f78053ff2d48e8f">9d366073f58559b41e63fa1d9f78053ff2d48e8f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/88/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/88/jenkins-report.html">here</a>.</h5></details></html>

2022-05-27 06:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/88/">test-portal-source-format#88</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/88/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/414">Sharryxue#414</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1862305701">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#414 - 2022-05-26[23:40:50]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/312/">publish-testray-report#312</a><br/></div></div>

2022-05-30 05:28 UTC, Sharryxue commented
Just starting review.

2022-05-30 05:42 UTC, Sharryxue requested changes
Hello @melodywu ,
The 2 locator can be combined by using *, please try t combine them to see if it works for other tests, thanks.

2022-05-30 05:42 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/userbar/UserBar.path
> +	<td>//div[contains(@class,'dropdown-menu-personal-menu') and contains(@class,'show')]//a[contains(.,'${key_dropdownItem}')] | //div[contains(@class,'dropdown-menu-personal-menu') and contains(@class
Please try to combine these 2 locator, thanks.

2022-05-30 08:24 UTC, melodywu commented
ci:test:sf

2022-05-30 08:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/1548/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/1548/jenkins-report.html">here</a>.</b></p>

2022-05-30 08:27 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/39a09a4346ea519c076c1828a5a0dda4a67c4ecb">39a09a4346ea519c076c1828a5a0dda4a67c4ecb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-75272">master-qa-75272</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/d8219a8ed6cc27e88f4dfc8b0c9c06a3633f6932">d8219a8ed6cc27e88f4dfc8b0c9c06a3633f6932</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/1548/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/1548/jenkins-report.html">here</a>.</h5></details></html>

2022-05-30 08:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/1548/">test-portal-source-format#1548</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/1548/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/414">Sharryxue#414</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1864391681">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#414 - 2022-05-30[01:24:34]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/5985/">publish-testray-report#5985</a><br/></div></div>

2022-05-30 12:15 UTC, Sharryxue commented
Just starting review.

2022-05-30 13:54 UTC, Sharryxue commented
No changes needed. Rebase and resend.
https://github.com/Sharryxue/liferay-portal/pull/416

2022-05-30 13:54 UTC, closed without merging