LRQA-75274 | master
Sharryxue/liferay-portal pull request #415
Opened 2022-05-30 09:01 UTC by melodywu

https://issues.liferay.com/browse/LRQA-75274

2022-05-30 09:01 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-05-30 09:01 UTC, melodywu commented
ci:test:sf

2022-05-30 09:04 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/39a09a4346ea519c076c1828a5a0dda4a67c4ecb">39a09a4346ea519c076c1828a5a0dda4a67c4ecb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-75274">master-qa-75274</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/2aab9240d7358d126c4a924e5465f84b496cd9bf">2aab9240d7358d126c4a924e5465f84b496cd9bf</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/612/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/612/jenkins-report.html">here</a>.</h5></details></html>

2022-05-30 09:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/612/">test-portal-source-format#612</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/612/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/415">Sharryxue#415</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1864393699">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#415 - 2022-05-30[02:01:52]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/2071/">publish-testray-report#2071</a><br/></div></div>

2022-05-30 12:47 UTC, Sharryxue commented
Just starting review.

2022-05-30 12:49 UTC, Sharryxue requested changes
Hello @melodywu,
Need more details for the fix. Thanks

2022-05-30 12:49 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/paths/pathlib/uisections/Treeview.path
> +	<td>xpath=(//div[contains(@role,'treeitem') and contains(@class,'collapsed')] | //div[contains(@role,'treeitem') and contains(@class,'active')])//div[contains(@class,'component-text')][normalize-spa
Why all of these three locators need update? Since only one locator should be used in this case.

2022-05-31 05:51 UTC, melodywu commented
ci:test:sf

2022-05-31 05:52 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/2213/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2213/jenkins-report.html">here</a>.</b></p>

2022-05-31 05:54 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9524594e69c82009cc3876bbb2aa3b2cae474780">9524594e69c82009cc3876bbb2aa3b2cae474780</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-75274">master-qa-75274</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/e92dfadcff8495c62c23dcaccaf1cd949fb30071">e92dfadcff8495c62c23dcaccaf1cd949fb30071</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2213/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2213/jenkins-report.html">here</a>.</h5></details></html>

2022-05-31 05:56 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2213/">test-portal-source-format#2213</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2213/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/415">Sharryxue#415</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1865173484">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#415 - 2022-05-30[22:51:45]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/7997/">publish-testray-report#7997</a><br/></div></div>

2022-05-31 07:14 UTC, melodywu commented
ci:test:sf

2022-05-31 07:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/638/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/638/jenkins-report.html">here</a>.</b></p>

2022-05-31 07:17 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9524594e69c82009cc3876bbb2aa3b2cae474780">9524594e69c82009cc3876bbb2aa3b2cae474780</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-75274">master-qa-75274</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/e896dbe44aac0c533c0ae5c1c55dd0f9113a5e52">e896dbe44aac0c533c0ae5c1c55dd0f9113a5e52</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/638/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/638/jenkins-report.html">here</a>.</h5></details></html>

2022-05-31 07:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/638/">test-portal-source-format#638</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/638/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/415">Sharryxue#415</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1865219628">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#415 - 2022-05-31[00:14:57]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/2131/">publish-testray-report#2131</a><br/></div></div>

2022-06-01 02:26 UTC, Sharryxue commented
Just starting review.

2022-06-01 02:40 UTC, Sharryxue commented
No changes needed.

2022-06-01 15:07 UTC, Sharryxue commented
Rebase and resend [Sharryxue/liferay-portal#418](https://github.com/Sharryxue/liferay-portal/pull/418).

2022-06-01 15:07 UTC, closed without merging