LRQA-73392 | master
Sharryxue/liferay-portal pull request #419
Opened 2022-06-06 23:07 UTC by epark18

https://issues.liferay.com/browse/LRQA-73392

2022-06-06 23:07 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-06-06 23:07 UTC, epark18 commented
ci:test:sf

2022-06-06 23:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/802/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/802/jenkins-report.html">here</a>.</b></p>

2022-06-06 23:11 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3720f69f017f294dda46ecfa6ee722fc76836fc1">3720f69f017f294dda46ecfa6ee722fc76836fc1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/epark18/liferay-portal/tree/LRQA-73392">LRQA-73392</a><br/>Branch GIT ID: <a href="https://github.com/epark18/liferay-portal/commit/44b0ccef5f3b603a3cbceb25c7bde0077c612963">44b0ccef5f3b603a3cbceb25c7bde0077c612963</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/802/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/802/jenkins-report.html">here</a>.</h5></details></html>

2022-06-06 23:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/802/">test-portal-source-format#802</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/802/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/419">Sharryxue#419</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1870204033">[master] ci:test:sf - epark18 &gt; Sharryxue - PR#419 - 2022-06-06[16:07:56]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/2604/">publish-testray-report#2604</a><br/></div></div>

2022-06-07 06:50 UTC, Sharryxue commented
Just starting review.

2022-06-07 07:01 UTC, Sharryxue requested changes
Hello @epark18,
We can add one more step to make the test more complicated. Please refer to my comments, thanks in advance.

2022-06-07 07:01 UTC, Sharryxue commented on modules/apps/portal-language/portal-language-override-test/src/testFunctional/tests/LanguageOverride.testcase
> +				locator1 = "LanguageOverride#VIEW_PAGE_LANGUAGE_KEY");
Please double check if this can be replaced by the exist locator _LexiconList#LIST_ENTRY_TITLE_, if yes, please also use the exist macro instead.

2022-06-07 07:01 UTC, Sharryxue commented on modules/apps/portal-language/portal-language-override-test/src/testFunctional/tests/LanguageOverride.testcase
> +				locator1 = "LanguageOverride#VIEW_PAGE_LANGUAGE_KEY");
Add a step to filter by a _languageKey_ without override and assert _No language entries were found._ displays.
Or add the assert step just after (filterBy = "Selected Language"). Thanks.

2022-06-13 02:46 UTC, Sharryxue commented
Just starting review.

2022-06-13 02:53 UTC, Sharryxue commented
No changes needed.

2022-06-14 23:28 UTC, Sharryxue commented
Rebase and resend. [Sharryxue/liferay-portal#422](https://github.com/Sharryxue/liferay-portal/pull/422).

2022-06-14 23:28 UTC, closed without merging