LRQA-66115 | master
Sharryxue/liferay-portal pull request #420
Opened 2022-06-09 02:20 UTC by melodywu

https://issues.liferay.com/browse/LRQA-66115

2022-06-09 02:20 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-06-09 02:20 UTC, melodywu commented
ci:test:sf

2022-06-09 02:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/1690/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/1690/jenkins-report.html">here</a>.</b></p>

2022-06-09 02:24 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/81069f1cbe4c578eecbd87ab25b380a1ef80b868">81069f1cbe4c578eecbd87ab25b380a1ef80b868</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-66115-1">master-qa-66115-1</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/36535b49988edc9c6f8b6ec423b9eedc99d404ff">36535b49988edc9c6f8b6ec423b9eedc99d404ff</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/1690/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/1690/jenkins-report.html">here</a>.</h5></details></html>

2022-06-09 02:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/1690/">test-portal-source-format#1690</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/1690/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/420">Sharryxue#420</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1872790100">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#420 - 2022-06-08[19:20:46]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/6459/">publish-testray-report#6459</a><br/></div></div>

2022-06-10 05:49 UTC, melodywu commented
ci:test:sf

2022-06-10 05:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/921/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/921/jenkins-report.html">here</a>.</b></p>

2022-06-10 05:52 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ba48e15384e0f799969dc3fcc38bc804535b505b">ba48e15384e0f799969dc3fcc38bc804535b505b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-66115-1">master-qa-66115-1</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/cfd12e884cc182a69bd7a21037bbe95da1e8e803">cfd12e884cc182a69bd7a21037bbe95da1e8e803</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/921/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/921/jenkins-report.html">here</a>.</h5></details></html>

2022-06-10 06:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/921/">test-portal-source-format#921</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/921/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/420">Sharryxue#420</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1874353163">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#420 - 2022-06-09[22:49:19]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/2936/">publish-testray-report#2936</a><br/></div></div>

2022-06-10 06:22 UTC, Sharryxue commented
Just starting review.

2022-06-13 02:06 UTC, Sharryxue requested changes
Hello @melodywu,
Could you please double check if these 2 tests can be combined, and see if the Filter by Price tests can also be covered here? Thanks in advance.
BTW, the BDD model start with Given.

2022-06-13 02:06 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/controlpanel/apps/appmanager/AppManagement.testcase
> +		task ("When user login marketplace store assert user login in Purchased page") {
Please start with Given in task when applying the BDD mode. Thanks

2022-06-13 02:06 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/controlpanel/apps/appmanager/AppManagement.testcase
> +	test ViewPurchasedApp {
Seems this 2 tests can be combined. The previous can be partial of this one. Could you try to combining the steps? Thanks in advance.

2022-06-13 02:06 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/controlpanel/apps/appmanager/AppManagement.testcase
> +			AppManager.purchaseApp(
See if this is duplicate with the filter by price test. Thanks

2022-06-13 06:36 UTC, melodywu commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/controlpanel/apps/appmanager/AppManagement.testcase
> +		task ("When user login marketplace store assert user login in Purchased page") {
combine search and filter by price tests

2022-06-13 06:46 UTC, closed without merging

2022-06-13 07:02 UTC, melodywu commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/controlpanel/apps/appmanager/AppManagement.testcase
> +	test ViewPurchasedApp {
ok and done

2022-06-13 13:36 UTC, Sharryxue commented
Resend [Sharryxue/liferay-portal#421](https://github.com/Sharryxue/liferay-portal/pull/420).