LRQA-74391 | master
Sharryxue/liferay-portal pull request #423
Opened 2022-06-14 07:47 UTC by lilylcl

https://issues.liferay.com/browse/LRQA-74391

2022-06-14 07:47 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-06-14 07:47 UTC, lilylcl commented
ci:test:sf

2022-06-14 07:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/1000/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/1000/jenkins-report.html">here</a>.</b></p>

2022-06-14 07:50 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/dd765e85673ab456e6522e05392d85173a8de6b0">dd765e85673ab456e6522e05392d85173a8de6b0</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/lilylcl/liferay-portal/tree/LRQA-74391">LRQA-74391</a><br/>Branch GIT ID: <a href="https://github.com/lilylcl/liferay-portal/commit/4f1086ab071d5fc20c6f984633ecf43d8b3cccdb">4f1086ab071d5fc20c6f984633ecf43d8b3cccdb</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/1000/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/1000/jenkins-report.html">here</a>.</h5></details></html>

2022-06-14 07:56 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/1000/">test-portal-source-format#1000</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/1000/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/423">Sharryxue#423</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1877804143">[master] ci:test:sf - lilylcl &gt; Sharryxue - PR#423 - 2022-06-14[00:47:57]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/3215/">publish-testray-report#3215</a><br/></div></div>

2022-06-15 07:31 UTC, Sharryxue commented
Just starting review.

2022-06-21 05:49 UTC, Sharryxue requested changes
Hello @lilylcl,
Good job for starting the NAT, there are things need changes, please refer to the comments. Thanks.

2022-06-21 05:49 UTC, Sharryxue commented on modules/apps/portal-language/portal-language-override-test/src/testFunctional/paths/LanguageOverride.path
> +	<td>OPTIONS_ELLIPSIS</td>
The locator should be duplicate.

2022-06-21 05:49 UTC, Sharryxue commented on modules/apps/portal-language/portal-language-override-test/src/testFunctional/paths/LanguageOverride.path
> +	<td>EXPORT_OVERRIDDEN_TRANSLATIONS_OPTION</td>
Same as this one.

2022-06-21 05:49 UTC, Sharryxue commented on modules/apps/portal-language/portal-language-override-test/src/testFunctional/macros/LanguageOverride.macro
> +	macro openOptionsMenu {
There should be an available macro for use.

2022-06-21 05:49 UTC, Sharryxue commented on modules/apps/portal-language/portal-language-override-test/src/testFunctional/tests/LanguageOverrideExportImport.testcase
> +		LanguageOverride.addLanguageKey(
Apply the BDD mode to tests.

2022-06-21 09:02 UTC, lilylcl commented
All done and push again, thanks @Sharryxue for review!

2022-06-21 09:02 UTC, lilylcl commented
ci:test:sf

2022-06-21 09:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/2405/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2405/jenkins-report.html">here</a>.</b></p>

2022-06-21 09:06 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2dae8872b8384a717a9a648a2753b3ad50c39f5f">2dae8872b8384a717a9a648a2753b3ad50c39f5f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/lilylcl/liferay-portal/tree/LRQA-74391">LRQA-74391</a><br/>Branch GIT ID: <a href="https://github.com/lilylcl/liferay-portal/commit/9a206d1096017de2c4292fe198f9514ba3bd9a62">9a206d1096017de2c4292fe198f9514ba3bd9a62</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2405/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2405/jenkins-report.html">here</a>.</h5></details></html>

2022-06-21 09:08 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2405/">test-portal-source-format#2405</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2405/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/423">Sharryxue#423</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1884283679">[master] ci:test:sf - lilylcl &gt; Sharryxue - PR#423 - 2022-06-21[02:02:57]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/8695/">publish-testray-report#8695</a><br/></div></div>

2022-06-21 11:48 UTC, Sharryxue commented
Just starting review.

2022-06-21 11:51 UTC, Sharryxue requested changes
Hello @lilylcl ,
Please add a step a view no Export option by default. Thanks.

2022-06-21 11:51 UTC, Sharryxue commented on modules/apps/portal-language/portal-language-override-test/src/testFunctional/tests/LanguageOverrideExportImport.testcase
> +		task ("When a new language keys is created") {
The BDD mode start with Given, and goes to When, end with Then.

2022-06-21 11:51 UTC, Sharryxue commented on modules/apps/portal-language/portal-language-override-test/src/testFunctional/tests/LanguageOverrideExportImport.testcase
> +	test CanViewExportOptionWhenHasOverride {
Please add a step to view the Export option not show up by default.

2022-06-21 11:51 UTC, Sharryxue commented on modules/apps/portal-language/portal-language-override-test/src/testFunctional/tests/LanguageOverrideExportImport.testcase
> +			Portlet.viewPortletOptions(optionsName = "Export Overridden Translations");
Great job for finding the exist macro.

2022-06-22 05:10 UTC, lilylcl commented
Resend https://github.com/Sharryxue/liferay-portal/pull/423.

2022-06-22 05:13 UTC, closed without merging

2022-07-12 02:27 UTC, lilylcl commented
Resend https://github.com/Sharryxue/liferay-portal/pull/452