LRQA-73501 | master
Sharryxue/liferay-portal pull request #428
Opened 2022-06-17 06:37 UTC by melodywu

https://issues.liferay.com/browse/LRQA-73501

2022-06-17 06:37 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-06-17 06:37 UTC, melodywu commented
ci:test:sf

2022-06-17 06:40 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/1293/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/1293/jenkins-report.html">here</a>.</b></p>

2022-06-17 06:42 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c5ba84afae8f4158e00bfa016741a668afee2067">c5ba84afae8f4158e00bfa016741a668afee2067</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-73501">master-qa-73501</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/82352f46a8731c837dc8da37b5d69385c730fddc">82352f46a8731c837dc8da37b5d69385c730fddc</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/1293/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/1293/jenkins-report.html">here</a>.</h5></details></html>

2022-06-17 06:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/1293/">test-portal-source-format#1293</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/1293/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/428">Sharryxue#428</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1881528498">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#428 - 2022-06-16[23:38:13]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/4907/">publish-testray-report#4907</a><br/></div></div>

2022-06-20 13:03 UTC, Sharryxue commented
Just starting review.

2022-06-20 13:04 UTC, Sharryxue requested changes
Hello @melodywu,
Please add step to assert another language key not shows up after searching. Thanks

2022-06-20 13:04 UTC, Sharryxue commented on modules/apps/portal-language/portal-language-override-test/src/testFunctional/tests/LanguageOverride.testcase
> +				value1 = "Languages With Override: es_ES, fr_FR, en_US");
It would be good to also assert another language key not shows up. Thanks

2022-06-24 02:10 UTC, closed without merging

2022-06-24 02:12 UTC, melodywu commented on modules/apps/portal-language/portal-language-override-test/src/testFunctional/tests/LanguageOverride.testcase
> +				value1 = "Languages With Override: es_ES, fr_FR, en_US");
done