LRQA-75809 | master
Sharryxue/liferay-portal pull request #446
Opened 2022-07-04 02:33 UTC by melodywu

https://issues.liferay.com/browse/LRQA-75809

2022-07-04 02:33 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-07-04 03:47 UTC, Sharryxue commented
ci:test:sf

2022-07-04 03:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/2461/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/2461/jenkins-report.html">here</a>.</b></p>

2022-07-04 03:49 UTC, Sharryxue commented
Just starting review.

2022-07-04 03:51 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/54f7e7969bb6596bc28b5e98da974efddd658438">54f7e7969bb6596bc28b5e98da974efddd658438</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-75809">master-qa-75809</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/dc2cab6266028fd5b6c900003b2cd3dd4f7fbbe9">dc2cab6266028fd5b6c900003b2cd3dd4f7fbbe9</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/2461/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/2461/jenkins-report.html">here</a>.</h5></details></html>

2022-07-04 03:53 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/2461/">test-portal-source-format#2461</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/2461/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/446">Sharryxue#446</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1895763579">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#446 - 2022-07-03[20:47:49]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/9115/">publish-testray-report#9115</a><br/></div></div>

2022-07-04 05:14 UTC, Sharryxue requested changes
Hello @melodywu,
Could you try if the waitForElementPresent function works for this? Thanks in advance.

2022-07-04 05:14 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/macros/AppManager.macro
> +		while (IsElementNotPresent(key_text = "Email Address", locator1 = "AppManager#LOGIN_INPUT_FIELD")) {
How about change this to use waitForElementPresent function?

2022-07-05 02:00 UTC, melodywu commented on portal-web/test/functional/com/liferay/portalweb/macros/AppManager.macro
> +		while (IsElementNotPresent(key_text = "Email Address", locator1 = "AppManager#LOGIN_INPUT_FIELD")) {
done

2022-07-05 02:00 UTC, melodywu commented
ci:test

2022-07-05 02:01 UTC, melodywu commented
ci:test:sf

2022-07-05 02:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-9.liferay.com/job/test-portal-source-format/3869/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/3869/jenkins-report.html">here</a>.</b></p>

2022-07-05 02:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>default</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/1987/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1987/jenkins-report.html">here</a>.</b></p>

2022-07-05 02:05 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5f16a4cd2b2f1fe7611530635ab79f69c9f8ac60">5f16a4cd2b2f1fe7611530635ab79f69c9f8ac60</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-75809">master-qa-75809</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/17664486d0470f62ea3a58a4840ac9aa930a6aed">17664486d0470f62ea3a58a4840ac9aa930a6aed</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-9.liferay.com/job/test-portal-source-format/3869/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/3869/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./portal-web/test/functional/com/liferay/portalweb/macros/AppManager.macro expected:&lt;...itForElementPresent([
     [java]       key_text = "Email Address",
     [java]       ]locator1 = "AppManag...&gt; but was:&lt;...itForElementPresent([key_text = "Email Address", ]locator1 = "AppManag...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:442)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:284)
[stopwatch] [run.batch.test.action: 1:55.527 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:450: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:593: Java returned: 1
      [get] Getting: http://test-1-9/job/test-portal-source-format/3869//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20220704193428997.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20220704193428997.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null547086108.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null156564428
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 250ms
[junitreport] Deleting: /tmp/null156564428
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 07-04-2022 19:34:32:877 PDT
[stopwatch] [run.batch.test.tear.down: 0.000 sec]</pre></details></html>

2022-07-05 02:08 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-9.liferay.com/job/test-portal-source-format/3869/">test-portal-source-format#3869</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/3869/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/446">Sharryxue#446</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1896521403">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#446 - 2022-07-04[19:01:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-9.liferay.com/job/publish-testray-report/3787/">publish-testray-report#3787</a><br/></div></div>

2022-07-05 02:50 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:default - 1 out of 3 jobs passed in 47 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/3498">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1387401_1987</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5f16a4cd2b2f1fe7611530635ab79f69c9f8ac60">5f16a4cd2b2f1fe7611530635ab79f69c9f8ac60</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6730f3ce0bcfbbd99c4e8d1aef9f3a16cbca7019">6730f3ce0bcfbbd99c4e8d1aef9f3a16cbca7019</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3497">Acceptance Upstream DXP (master) #3497</a></p><details><summary><strong>ci:test:default - 1 out of 3 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/1987/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/97398/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li></ul></li></ul></div><details><summary><strong>1 Successful Jobs:</strong></summary><ul><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/100619/">functional-tomcat90-mysql57-jdk8/0/0</a></li></ul></li></ul></details></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1987/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/97398//consoleText">functional-tomcat90-mysql57-jdk8/0/1</a><ol><li><div><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/97398//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_AppManagement_ViewPurchasedApp_">LocalFile.AppManagement#ViewPurchasedApp</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-07/test-1-38/test-portal-acceptance-pullrequest(master)/1987/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.AppManagement_ViewPurchasedApp/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-07/test-1-38/test-portal-acceptance-pullrequest(master)/1987/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.AppManagement_ViewPurchasedApp/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-07/test-1-38/test-portal-acceptance-pullrequest(master)/1987/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2022-07-05 02:52 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/1987/">test-portal-acceptance-pullrequest(master)#1987</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1987/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>default<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/446">Sharryxue#446</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1896537963">[master] ci:test:default - melodywu &gt; Sharryxue - PR#446 - 2022-07-04[19:03:17]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/4659/">publish-testray-report#4659</a><br/></div></div>

2022-07-05 05:21 UTC, melodywu commented
ci:test:sf

2022-07-05 05:21 UTC, melodywu commented
ci:test

2022-07-05 05:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>default</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/2234/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2234/jenkins-report.html">here</a>.</b></p>

2022-07-05 05:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-19.liferay.com/job/test-portal-source-format/6374/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/6374/jenkins-report.html">here</a>.</b></p>

2022-07-05 05:26 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/49dd416c5571998d3b039481151cc00ebe94abb1">49dd416c5571998d3b039481151cc00ebe94abb1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-75809">master-qa-75809</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/92aa1224a4973447845dfffa6b4f0866c1966a7d">92aa1224a4973447845dfffa6b4f0866c1966a7d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-19.liferay.com/job/test-portal-source-format/6374/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/6374/jenkins-report.html">here</a>.</h5></details></html>

2022-07-05 05:28 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-19.liferay.com/job/test-portal-source-format/6374/">test-portal-source-format#6374</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/6374/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/446">Sharryxue#446</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1896612498">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#446 - 2022-07-04[22:21:45]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-19.liferay.com/job/publish-testray-report/2645/">publish-testray-report#2645</a><br/></div></div>

2022-07-05 06:42 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:default - 1 out of 3 jobs passed in 1 hour 20 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/3499">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1347401_2234</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/49dd416c5571998d3b039481151cc00ebe94abb1">49dd416c5571998d3b039481151cc00ebe94abb1</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5f16a4cd2b2f1fe7611530635ab79f69c9f8ac60">5f16a4cd2b2f1fe7611530635ab79f69c9f8ac60</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3498">Acceptance Upstream DXP (master) #3498</a></p><details><summary><strong>ci:test:default - 1 out of 3 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/2234/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/41515/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li></ul></li></ul></div><details><summary><strong>1 Successful Jobs:</strong></summary><ul><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/41892/">functional-tomcat90-mysql57-jdk8/0/0</a></li></ul></li></ul></details></details><h5>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2234/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/41515//consoleText">functional-tomcat90-mysql57-jdk8/0/1</a><ol><li><div><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/41515//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_AppManagement_ViewPurchasedApp_">LocalFile.AppManagement#ViewPurchasedApp</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-07/test-1-34/test-portal-acceptance-pullrequest(master)/2234/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.AppManagement_ViewPurchasedApp/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-07/test-1-34/test-portal-acceptance-pullrequest(master)/2234/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.AppManagement_ViewPurchasedApp/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-07/test-1-34/test-portal-acceptance-pullrequest(master)/2234/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2022-07-05 06:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/2234/">test-portal-acceptance-pullrequest(master)#2234</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2234/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>default<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/446">Sharryxue#446</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1896675196">[master] ci:test:default - melodywu &gt; Sharryxue - PR#446 - 2022-07-04[22:21:51]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/5878/">publish-testray-report#5878</a><br/></div></div>

2022-07-05 23:47 UTC, melodywu commented
ci:test

2022-07-06 00:34 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>default</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/3208/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3208/jenkins-report.html">here</a>.</b></p>

2022-07-06 02:23 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:default - 1 out of 3 jobs passed in 1 hour 49 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/3504">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1377401_3208</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/13c33439de3d9cf3cc5b3bbd871334f29c0a62f2">13c33439de3d9cf3cc5b3bbd871334f29c0a62f2</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f23a657acc858ecbda7cbb1559e862fdd3be1052">f23a657acc858ecbda7cbb1559e862fdd3be1052</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3502">Acceptance Upstream DXP (master) #3502</a></p><details><summary><strong>ci:test:default - 1 out of 3 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/3208/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/94706/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li></ul></li></ul></div><details><summary><strong>1 Successful Jobs:</strong></summary><ul><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/94707/">functional-tomcat90-mysql57-jdk8/0/0</a></li></ul></li></ul></details></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3208/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/94706//consoleText">functional-tomcat90-mysql57-jdk8/0/1</a><ol><li><div><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/94706//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_AppManagement_ViewPurchasedApp_">LocalFile.AppManagement#ViewPurchasedApp</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-07/test-1-37/test-portal-acceptance-pullrequest(master)/3208/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.AppManagement_ViewPurchasedApp/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-07/test-1-37/test-portal-acceptance-pullrequest(master)/3208/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.AppManagement_ViewPurchasedApp/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-07/test-1-37/test-portal-acceptance-pullrequest(master)/3208/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2022-07-06 02:25 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/3208/">test-portal-acceptance-pullrequest(master)#3208</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3208/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>default<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/446">Sharryxue#446</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1897429809">[master] ci:test:default - melodywu &gt; Sharryxue - PR#446 - 2022-07-05[17:34:13]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/7726/">publish-testray-report#7726</a><br/></div></div>

2022-07-07 00:41 UTC, melodywu commented
ci:test:sf

2022-07-07 00:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/2543/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2543/jenkins-report.html">here</a>.</b></p>

2022-07-07 00:44 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7c9d5f0a44e33dcdcdf459d76dc6124b99e50d17">7c9d5f0a44e33dcdcdf459d76dc6124b99e50d17</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-75809">master-qa-75809</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/8861813511b686e950c8a6c6f458b78773519878">8861813511b686e950c8a6c6f458b78773519878</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2543/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2543/jenkins-report.html">here</a>.</h5></details></html>

2022-07-07 00:47 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2543/">test-portal-source-format#2543</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2543/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/446">Sharryxue#446</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1898563551">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#446 - 2022-07-06[17:41:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/9247/">publish-testray-report#9247</a><br/></div></div>

2022-07-12 08:00 UTC, Sharryxue commented
Just starting review.

2022-07-12 08:16 UTC, Sharryxue commented
No changes needed. :)

2022-07-13 14:57 UTC, Sharryxue commented
Rebase and resend.
https://github.com/Sharryxue/liferay-portal/pull/454

2022-07-13 14:57 UTC, closed without merging