LRQA-75075 | master
Sharryxue/liferay-portal pull request #448
Opened 2022-07-05 05:37 UTC by melodywu

https://issues.liferay.com/browse/LRQA-75075

2022-07-05 05:37 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-07-05 05:38 UTC, melodywu commented
ci:test:sf

2022-07-05 05:40 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-16.liferay.com/job/test-portal-source-format/6080/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/6080/jenkins-report.html">here</a>.</b></p>

2022-07-05 05:42 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/49dd416c5571998d3b039481151cc00ebe94abb1">49dd416c5571998d3b039481151cc00ebe94abb1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-75075">master-qa-75075</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/fc6ae11cdbd9a78d36da3d6edbaca047851d42fe">fc6ae11cdbd9a78d36da3d6edbaca047851d42fe</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-16.liferay.com/job/test-portal-source-format/6080/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/6080/jenkins-report.html">here</a>.</h5></details></html>

2022-07-05 05:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-16.liferay.com/job/test-portal-source-format/6080/">test-portal-source-format#6080</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-source-format/builds/6080/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/448">Sharryxue#448</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1896623777">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#448 - 2022-07-04[22:38:23]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-16.liferay.com/job/publish-testray-report/2446/">publish-testray-report#2446</a><br/></div></div>

2022-07-05 06:15 UTC, Sharryxue commented
Just starting review.

2022-07-06 08:34 UTC, Sharryxue requested changes
Hello @melodywu,
There are some changes needed, please refer to the comment. Thanks.

2022-07-06 08:34 UTC, Sharryxue commented on modules/apps/portal-language/portal-language-override-test/src/testFunctional/tests/LanguageOverride.testcase
> +			AssertTextEquals(
Use exist macro instead.

2022-07-06 08:34 UTC, Sharryxue commented on modules/apps/portal-language/portal-language-override-test/src/testFunctional/tests/LanguageOverride.testcase
> +			AssertTextEquals(
Same here.

2022-07-06 08:34 UTC, Sharryxue commented on modules/apps/portal-language/portal-language-override-test/src/testFunctional/tests/LanguageOverride.testcase
> +	@description = "It asserts the translation proper override info of new language key."
Please make the description clearly.

2022-07-06 08:34 UTC, Sharryxue commented on modules/apps/portal-language/portal-language-override-test/src/testFunctional/tests/LanguageOverride.testcase
> +		task ("Given one new language keys are created with all language override translations") {
_one new language keys are_ should be _one new language key is_.

2022-07-06 08:34 UTC, Sharryxue commented on modules/apps/portal-language/portal-language-override-test/src/testFunctional/tests/LanguageOverride.testcase
> +		}
Sorry, but shall we put the assert translation of the language key step here, thanks.

2022-07-07 05:48 UTC, melodywu commented
ci:test:sf

2022-07-07 05:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/2771/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/2771/jenkins-report.html">here</a>.</b></p>

2022-07-07 05:51 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ff72a17ea61cf3260c8a526e3d8b2904e09f5623">ff72a17ea61cf3260c8a526e3d8b2904e09f5623</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-75075">master-qa-75075</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/46b565634acbe158ec01eae4c6690ece759d11ce">46b565634acbe158ec01eae4c6690ece759d11ce</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/2771/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/2771/jenkins-report.html">here</a>.</h5></details></html>

2022-07-07 05:54 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/2771/">test-portal-source-format#2771</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/2771/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/448">Sharryxue#448</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1898890651">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#448 - 2022-07-06[22:48:38]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/10231/">publish-testray-report#10231</a><br/></div></div>

2022-07-12 08:16 UTC, Sharryxue commented
Just starting review.

2022-07-12 08:22 UTC, Sharryxue requested changes
Hello @melodywu,
Please use the exist macro in test, thanks.
And need ignore the test due to LPS-157770.

2022-07-12 08:22 UTC, Sharryxue commented on modules/apps/portal-language/portal-language-override-test/src/testFunctional/tests/LanguageOverride.testcase
> +			AssertTextEquals(
See if the _LexiconList.viewListEntrySubtitle_ macro or other macro in _LexiconList.macro_ file work, thanks.

2022-07-12 08:22 UTC, Sharryxue commented on modules/apps/portal-language/portal-language-override-test/src/testFunctional/tests/LanguageOverride.testcase
> +			LexiconEntry.viewEntryName(rowEntry = "mês");
Use the _LexiconList.viewListEntrySubtitle_ to replace if it works, since _LexiconEntry.viewEntryName_ makes others misunderstand.

2022-07-13 02:28 UTC, melodywu commented
ci:test:sf

2022-07-13 02:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/3046/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/3046/jenkins-report.html">here</a>.</b></p>

2022-07-13 02:33 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e331634776d3e67d5f377bd8d42112568466b47b">e331634776d3e67d5f377bd8d42112568466b47b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-75075">master-qa-75075</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/51b00867067a836a6a8f024ce96da45509130717">51b00867067a836a6a8f024ce96da45509130717</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/3046/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/3046/jenkins-report.html">here</a>.</h5></details></html>

2022-07-13 02:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/3046/">test-portal-source-format#3046</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/3046/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/448">Sharryxue#448</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1904716968">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#448 - 2022-07-12[19:28:49]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/11309/">publish-testray-report#11309</a><br/></div></div>

2022-07-13 06:42 UTC, melodywu commented
ci:test:sf

2022-07-13 06:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/1643/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/1643/jenkins-report.html">here</a>.</b></p>

2022-07-13 06:45 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d365f9baded97fa9119cb07f5e0342304bf6c298">d365f9baded97fa9119cb07f5e0342304bf6c298</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-75075">master-qa-75075</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/9f6c7908b0b6830927a09be05dfda07a3f67ffb7">9f6c7908b0b6830927a09be05dfda07a3f67ffb7</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/1643/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/1643/jenkins-report.html">here</a>.</h5></details></html>

2022-07-13 06:47 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/1643/">test-portal-source-format#1643</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/1643/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/448">Sharryxue#448</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1904899870">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#448 - 2022-07-12[23:42:10]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/5232/">publish-testray-report#5232</a><br/></div></div>

2022-07-13 14:46 UTC, Sharryxue commented
Just starting review.

2022-07-13 14:49 UTC, Sharryxue commented
Need one more commit to ignore the test for LPS-157770/

2022-07-14 01:03 UTC, melodywu commented
ci:test:sf

2022-07-14 01:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/2597/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2597/jenkins-report.html">here</a>.</b></p>

2022-07-14 01:07 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d365f9baded97fa9119cb07f5e0342304bf6c298">d365f9baded97fa9119cb07f5e0342304bf6c298</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-75075">master-qa-75075</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/8b954d31e5310d0b8565d0f54f7a0b6df355d576">8b954d31e5310d0b8565d0f54f7a0b6df355d576</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2597/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2597/jenkins-report.html">here</a>.</h5></details></html>

2022-07-14 01:10 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2597/">test-portal-source-format#2597</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2597/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/448">Sharryxue#448</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1905930633">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#448 - 2022-07-13[18:04:06]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/9492/">publish-testray-report#9492</a><br/></div></div>

2022-07-14 08:47 UTC, Sharryxue commented
Just starting review.

2022-07-14 10:38 UTC, Sharryxue commented
Minor change for the commit message, no period in commit message.
View [21f804d](https://github.com/Sharryxue/liferay-portal/pull/455/commits/21f804dc42abf8d7cc6f6c3f4a4c686582b57827).

2022-07-14 10:38 UTC, closed without merging