LRQA-75074 | master
Sharryxue/liferay-portal pull request #449
Opened 2022-07-07 08:01 UTC by melodywu

https://issues.liferay.com/browse/LRQA-75074

2022-07-07 08:02 UTC, melodywu commented
ci:test:sf

2022-07-07 08:06 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6060b323abbae0fe362746d41395053fa847446f">6060b323abbae0fe362746d41395053fa847446f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-75074">master-qa-75074</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/02e031319f508adfa2ef5614948295e97b8e4ec4">02e031319f508adfa2ef5614948295e97b8e4ec4</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/2868/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/2868/jenkins-report.html">here</a>.</h5></details></html>

2022-07-07 08:08 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/2868/">test-portal-source-format#2868</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/2868/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/449">Sharryxue#449</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1898982484">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#449 - 2022-07-07[01:03:10]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/10243/">publish-testray-report#10243</a><br/></div></div>

2022-07-12 08:50 UTC, Sharryxue commented
Just starting review.

2022-07-12 08:51 UTC, Sharryxue requested changes
Hello @melodywu,
Minor change required in the test, thanks.

2022-07-12 08:51 UTC, Sharryxue commented on modules/apps/portal-language/portal-language-override-test/src/testFunctional/tests/LanguageOverride.testcase
> +		task ("Then both keys should be present, but only the selected language 'nl-NL' should be bold and translation for language key display") {
Update _and translation for language key display_ to  _and translation in nl-NL display_

2022-07-12 08:51 UTC, Sharryxue commented on modules/apps/portal-language/portal-language-override-test/src/testFunctional/tests/LanguageOverride.testcase
> +			AssertElementPresent(
Use exist macro.

2022-07-13 02:47 UTC, melodywu commented
ci:test:sf

2022-07-13 02:48 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/2132/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/2132/jenkins-report.html">here</a>.</b></p>

2022-07-13 02:50 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e7f401e06bc437bf7b6fdb4befd8d47d46e63b50">e7f401e06bc437bf7b6fdb4befd8d47d46e63b50</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-75074">master-qa-75074</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/466714162374a6d16da7ededfb9182848e46fffc">466714162374a6d16da7ededfb9182848e46fffc</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/2132/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/2132/jenkins-report.html">here</a>.</h5></details></html>

2022-07-13 02:54 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/2132/">test-portal-source-format#2132</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/2132/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/449">Sharryxue#449</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1904751618">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#449 - 2022-07-12[19:47:52]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/8078/">publish-testray-report#8078</a><br/></div></div>

2022-07-13 14:48 UTC, Sharryxue commented
Just starting review.

2022-07-13 14:57 UTC, Sharryxue commented
No changes needed.

2022-07-13 14:57 UTC, Sharryxue commented
Rebase and resend.
https://github.com/Sharryxue/liferay-portal/pull/454

2022-07-13 14:57 UTC, closed without merging