LRQA-73679 | master
Sharryxue/liferay-portal pull request #456
Opened 2022-07-18 08:00 UTC by melodywu

https://issues.liferay.com/browse/LRQA-73679

2022-07-18 08:00 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-07-18 08:00 UTC, melodywu commented
ci:test:sf

2022-07-18 08:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-15.liferay.com/job/test-portal-source-format/3804/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/3804/jenkins-report.html">here</a>.</b></p>

2022-07-18 08:04 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0d82204ad29375df9fa8d20e877f1a558d2afc5a">0d82204ad29375df9fa8d20e877f1a558d2afc5a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-73679">master-qa-73679</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/6ed0233d345669b3fbc81f83803c9c381855f6de">6ed0233d345669b3fbc81f83803c9c381855f6de</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-15.liferay.com/job/test-portal-source-format/3804/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/3804/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: ./portal-web/test/functional/com/liferay/portalweb/paths/portlet/roles/RolesPermissions.path expected:&lt;...d&gt;
     [java]   &lt;td&gt;&lt;/td&gt;
     [java] &lt;/tr&gt;
     [java] []&lt;tr&gt;
     [java]   &lt;td&gt;ACCOUNTS_A...&gt; but was:&lt;...d&gt;
     [java]   &lt;td&gt;&lt;/td&gt;
     [java] &lt;/tr&gt;
     [java] [
     [java] ]&lt;tr&gt;
     [java]   &lt;td&gt;ACCOUNTS_A...&gt;
     [java] 2: Truncated message :
     [java] ./portal-web/test/functional/com/liferay/portalweb/macros/Role.macro expected:&lt;...\}");
     [java]   \}
     [java] 
     [java]   macro edit[AccountEntryDefinePermission \{
     [java]     if ((IsElementPresent.isElementPresentAfterWait(locator1 = "Message#INFO")) &amp;&amp; (IsVisible(locator1 = "Message#INFO"))) \{
     [java]       AssertTextEquals(
     [java]         locator1 = "Message#INFO",
     [java]         value1 = "This role does not have any permissions.");
     [java]     \}
     [java] 
     [java]     for (var permissionDefinitionKey : list "\$\{permissionDefinitionKeys\}") \{
     [java]       if (contains("\$\{permissionDefinitionKey\}", "ACCOUNTS_ACCOUNTS")) \{
     [java]         var key_navItem = "Accounts";
     [java]         var key_subItem = "Accounts";
     [java]       \}
     [java]       else if (contains("\$\{permissionDefinitionKey\}", "ACCOUNTS_ACCOUNTS_USERS")) \{
     [java]         var key_navItem = "Accounts";
     [java]         var key_subItem = "Accounts Users";
     [java]       \}
     [java]       else if (contains("\$\{permissionDefinitionKey\}", "ACCOUNTS_ACCOUNTS_GROUP")) \{
     [java]         var key_navItem = "Accounts";
     [java]         var key_subItem = "Accounts Groups";
     [java]       \}
     [java]       else if (contains("\$\{permissionDefinitionKey\}", "SITE_ADMIN_APPLICATIONS_ASSET_PUBLISHER")) \{
     [java]         var key_navItem = "Site and Asset Library Administration";
     [java]         var key_subItem = "Asset Publisher";
     [java]       \}
     [java] 
     [java]       if (!(IsElementPresent(locator1 = "RolesPermissions#\$\{permissionDefinitionKey\}"))) \{
     [java]         Type(
     [java]           locator1 = "RolesPermissionsNavigation#SEARCH_FIELD",
     [java]           value1 = "\$\{key_subItem\}");
     [java] 
     [java]         AssertClick(
     [java]           locator1 = "RolesPermissionsNavigation#PERMISSIONS_NAVITEM_SUBITEM",
     [java]           value1 = "\$\{key_subItem\}");
     [java]       \}
     [java] 
     [java]       if ("\$\{define\}" == "true") \{
     [java]         Check(locator1 = "RolesPermissions#\$\{permissionDefinitionKey\}");
     [java]       \}</pre></details></html>

2022-07-18 08:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-15.liferay.com/job/test-portal-source-format/3804/">test-portal-source-format#3804</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/3804/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/456">Sharryxue#456</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1909788245">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#456 - 2022-07-18[01:00:47]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-15.liferay.com/job/publish-testray-report/2690/">publish-testray-report#2690</a><br/></div></div>

2022-07-18 08:20 UTC, melodywu commented
ci:test:sf

2022-07-18 08:22 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/2199/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/2199/jenkins-report.html">here</a>.</b></p>

2022-07-18 08:24 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0d82204ad29375df9fa8d20e877f1a558d2afc5a">0d82204ad29375df9fa8d20e877f1a558d2afc5a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-73679">master-qa-73679</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/590505a8923bd8efd96a0843e3d99be5e991b54e">590505a8923bd8efd96a0843e3d99be5e991b54e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/2199/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/2199/jenkins-report.html">here</a>.</h5></details></html>

2022-07-18 08:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/2199/">test-portal-source-format#2199</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/2199/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/456">Sharryxue#456</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1909789507">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#456 - 2022-07-18[01:21:03]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/8339/">publish-testray-report#8339</a><br/></div></div>

2022-07-18 10:47 UTC, Sharryxue commented
Just starting review.

2022-07-29 07:47 UTC, Sharryxue requested changes
Hello @melodywu,
The new added macro is duplicate, and the test is trying to confirm the permission defined in Role Admin for account role works, please update the test, thanks.

2022-07-29 07:47 UTC, Sharryxue commented on modules/apps/account/account-test/src/testFunctional/macros/Accounts.macro
> +
This is a duplicate macro.

2022-07-29 07:47 UTC, Sharryxue commented on modules/apps/account/account-test/src/testFunctional/tests/AccountRoles.testcase
> +	@description = "This is a use case for LPS-144122. This asserts user can view account roles tab when accounts with permission."
Use the story ticket, instead of the manual testing ticket. Update the description as "This asserts user can view account roles tab with permissions". Thanks.

2022-07-29 07:47 UTC, Sharryxue commented on modules/apps/account/account-test/src/testFunctional/tests/AccountRoles.testcase
> +			JSONUser.setFirstPassword(
Is _property custom.properties = "jsonws.web.service.paths.excludes=";_ a required property for this macro?

2022-07-29 07:47 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/macros/Role.macro
> +	macro editAccountEntryDefinePermission {
Hello @melodywu,
I'd lost the context of why we need adding this macro, since it very similar to the exist macro of _Role.editPermissionCmdCP_, why we not adding new _else if_ condition for account related permissions? could you help me understand it? Thanks in advance.

2022-07-29 07:47 UTC, Sharryxue commented on modules/apps/account/account-test/src/testFunctional/tests/AccountRoles.testcase
> +			AssertTextEquals(
Since this is a Lexicon entry, please use the macro instead, thanks.

2022-07-29 07:47 UTC, Sharryxue commented on modules/apps/account/account-test/src/testFunctional/tests/AccountRoles.testcase
> +		task ("Then the user can view account and roles tab") {
Change the description to only indicate the User can view the Roles tab in Account.

2022-07-29 07:47 UTC, Sharryxue commented on modules/apps/account/account-test/src/testFunctional/tests/AccountRoles.testcase
> +		task ("Given add a user with permission of view CP and accounts") {
Can contain adding the View account role permission as well.

2022-07-29 07:47 UTC, Sharryxue commented on modules/apps/account/account-test/src/testFunctional/tests/AccountRoles.testcase
> +			Accounts.addOwnedAccountRole(accountRoleTitle = "Account Specific Role");
The permission for this test should be the one in Role Admin > Account Role, not the owned role in account. Thanks.

2022-08-04 07:55 UTC, melodywu commented
ci:test:sf

2022-08-04 08:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-source-format/6467/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/6467/jenkins-report.html">here</a>.</b></p>

2022-08-04 08:02 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/55d6ca02fa5b60003ff8db2045847f57ce063780">55d6ca02fa5b60003ff8db2045847f57ce063780</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-73679">master-qa-73679</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/03272232128240bf07cc0e0c704f131c6413c090">03272232128240bf07cc0e0c704f131c6413c090</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-source-format/6467/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/6467/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./portal-web/test/functional/com/liferay/portalweb/macros/json/roles/JSONRoleAPI.macro expected:&lt;...ition \{
     [java] 
     [java]   macro _add[AccountRole \{
     [java]     Variables.assertDefined(parameterList = "\$\{name\},\$\{titleMap\},\$\{descriptionMap\},\$\{type\}");
     [java] 
     [java]     var portalURL = JSONCompany.getPortalURL();
     [java] 
     [java]     var curl = '''
     [java]       \$\{portalURL\}/api/jsonws/role/add-role \
     [java]         -u [REDACTED]:test \
     [java]         -d className=com.liferay.account.model.AccountRole \
     [java]         -d classPK=0 \
     [java]         -d name=\$\{name\} \
     [java]         -d titleMap=\$\{titleMap\} \
     [java]         -d descriptionMap=\$\{descriptionMap\} \
     [java]         -d type=\$\{type\} \
     [java]         -d subtype=
     [java]     ''';
     [java] 
     [java]     com.liferay.poshi.runner.util.JSONCurlUtil.post("\$\{curl\}");
     [java]   \}
     [java] 
     [java]   macro _addRole \{
     [java]     Variables.assertDefined(parameterList = "\$\{name\},\$\{titleMap\},\$\{descriptionMap\},\$\{type\}");
     [java] 
     [java]     var portalURL = JSONCompany.getPortalURL();
     [java] 
     [java]     var curl = '''
     [java]       \$\{portalURL\}/api/jsonws/role/add-role \
     [java]         -u [REDACTED]:test \
     [java]         -d className=com.liferay.portal.kernel.model.]Role \
     [java]         -d classP...&gt; but was:&lt;...ition \{
     [java] 
     [java]   macro _add[Role \{
     [java]     Variables.assertDefined(parameterList = "\$\{name\},\$\{titleMap\},\$\{descriptionMap\},\$\{type\}");
     [java] 
     [java]     var portalURL = JSONCompany.getPortalURL();
     [java] 
     [java]     var curl = '''
     [java]       \$\{portalURL\}/api/jsonws/role/add-role \
     [java]         -u [REDACTED]:test \
     [java]         -d className=com.liferay.portal.kernel.model.Role \
     [java]         -d classPK=0 \
     [java]         -d name=\$\{name\} \
     [java]         -d titleMap=\$\{titleMap\} \
     [java]         -d descriptionMap=\$\{descriptionMap\} \
     [java]         -d type=\$\{type\} \
     [java]         -d subtype=
     [java]     ''';
     [java] 
     [java]     com.liferay.poshi.runner.util.JSONCurlUtil.post("\$\{curl\}");
     [java]   \}
     [java] 
     [java]   macro _addAccountRole \{
     [java]     Variables.assertDefined(parameterList = "\$\{name\},\$\{titleMap\},\$\{descriptionMap\},\$\{type\}");
     [java] 
     [java]     var portalURL = JSONCompany.getPortalURL();
     [java] 
     [java]     var curl = '''</pre></details></html>

2022-08-04 08:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-11.liferay.com/job/test-portal-source-format/6467/">test-portal-source-format#6467</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/6467/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/456">Sharryxue#456</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1936494926">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#456 - 2022-08-04[00:58:27]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-11.liferay.com/job/publish-testray-report/2775/">publish-testray-report#2775</a><br/></div></div>

2022-08-04 08:12 UTC, melodywu commented
ci:test:sf

2022-08-04 08:14 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/2871/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/2871/jenkins-report.html">here</a>.</b></p>

2022-08-04 08:16 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/55d6ca02fa5b60003ff8db2045847f57ce063780">55d6ca02fa5b60003ff8db2045847f57ce063780</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/melodywu/liferay-portal/tree/master-qa-73679">master-qa-73679</a><br/>Branch GIT ID: <a href="https://github.com/melodywu/liferay-portal/commit/cda5fbd224d36224722609cf077739aee5a4f63f">cda5fbd224d36224722609cf077739aee5a4f63f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/2871/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/2871/jenkins-report.html">here</a>.</h5></details></html>

2022-08-04 08:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/2871/">test-portal-source-format#2871</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/2871/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/456">Sharryxue#456</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1936495719">[master] ci:test:sf - melodywu &gt; Sharryxue - PR#456 - 2022-08-04[01:12:43]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/10418/">publish-testray-report#10418</a><br/></div></div>

2022-08-05 00:00 UTC, closed without merging