LRQA-75928 | master
Sharryxue/liferay-portal pull request #463
Opened 2022-07-28 06:02 UTC by chaowang-123

https://issues.liferay.com/browse/LRQA-75928
Submit to master.

2022-07-28 06:02 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-07-28 06:02 UTC, chaowang-123 commented
ci:test:sf

2022-07-28 06:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/3656/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/3656/jenkins-report.html">here</a>.</b></p>

2022-07-28 06:06 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/309e286c018e31767e55b343bb276e6104c72fbe">309e286c018e31767e55b343bb276e6104c72fbe</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/chaowang-123/liferay-portal/tree/master-qa-75928">master-qa-75928</a><br/>Branch GIT ID: <a href="https://github.com/chaowang-123/liferay-portal/commit/1a87862b7c9ebc4af11419b2e89e1f0d56ccfca0">1a87862b7c9ebc4af11419b2e89e1f0d56ccfca0</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/3656/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/3656/jenkins-report.html">here</a>.</h5></details></html>

2022-07-28 06:49 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/3656/">test-portal-source-format#3656</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/3656/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/463">Sharryxue#463</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1923401963">[master] ci:test:sf - chaowang-123 &gt; Sharryxue - PR#463 - 2022-07-27[23:02:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/13554/">publish-testray-report#13554</a><br/></div></div>

2022-08-01 14:41 UTC, Sharryxue commented
Just starting review.

2022-08-01 15:13 UTC, Sharryxue requested changes
Hello @chaowang-123 ,
Thanks for taking care of the test. There are minor changes needed before we submit the commit. Could you please take care of them? Thanks in advance.

2022-08-01 15:13 UTC, Sharryxue commented on modules/apps/account/account-test/src/testFunctional/tests/Accounts.testcase
> +	@description = "This test adds an account with an avatar."
It would be better to include the issue we wrote tests for in the description.

2022-08-01 15:13 UTC, Sharryxue commented on modules/apps/account/account-test/src/testFunctional/tests/Accounts.testcase
> +
Could you please add a step to confirm the uploaded file persist after clicking Done, thanks.

2022-08-02 04:02 UTC, chaowang-123 commented
ci:test:sf

2022-08-02 04:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/315/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/315/jenkins-report.html">here</a>.</b></p>

2022-08-02 04:07 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1e631d70095286d260c3a4ee149e979a643cc192">1e631d70095286d260c3a4ee149e979a643cc192</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/chaowang-123/liferay-portal/tree/master-qa-75928">master-qa-75928</a><br/>Branch GIT ID: <a href="https://github.com/chaowang-123/liferay-portal/commit/3502cbaec9a110683f6953fb473e817497b53f40">3502cbaec9a110683f6953fb473e817497b53f40</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/315/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/315/jenkins-report.html">here</a>.</h5></details></html>

2022-08-02 04:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/315/">test-portal-source-format#315</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/315/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/463">Sharryxue#463</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1933936644">[master] ci:test:sf - chaowang-123 &gt; Sharryxue - PR#463 - 2022-08-01[21:03:29]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/1072/">publish-testray-report#1072</a><br/></div></div>

2022-08-02 13:52 UTC, Sharryxue commented
Just starting review.

2022-08-10 07:41 UTC, Sharryxue commented
Minor changes in the description, squashed the commits.
View [725c76bd...de3a9335](https://github.com/liferay/liferay-portal/compare/725c76bd35f080ac4d8c96ad4b8f45939c997835%5E...de3a9335bd172dd7145759e7c98edc460ade7409).

2022-08-10 07:41 UTC, closed without merging