LRQA-74416 | master
Sharryxue/liferay-portal pull request #470
Opened 2022-08-02 15:18 UTC by epark18

https://issues.liferay.com/browse/LRQA-74416

2022-08-02 15:18 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-08-02 15:18 UTC, epark18 commented
ci:test:sf

2022-08-02 15:20 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-18.liferay.com/job/test-portal-source-format/6460/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/6460/jenkins-report.html">here</a>.</b></p>

2022-08-02 15:22 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/61f64632f1db723cfb4b73b68c9a211a93e2ccb8">61f64632f1db723cfb4b73b68c9a211a93e2ccb8</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/epark18/liferay-portal/tree/LRQA-74416">LRQA-74416</a><br/>Branch GIT ID: <a href="https://github.com/epark18/liferay-portal/commit/0febda446a0340d4d8ce6cc506c525ece994d89c">0febda446a0340d4d8ce6cc506c525ece994d89c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-source-format/6460/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/6460/jenkins-report.html">here</a>.</h5></details></html>

2022-08-02 15:25 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-18.liferay.com/job/test-portal-source-format/6460/">test-portal-source-format#6460</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/6460/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/470">Sharryxue#470</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1934429675">[master] ci:test:sf - epark18 &gt; Sharryxue - PR#470 - 2022-08-02[08:18:37]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-18.liferay.com/job/publish-testray-report/2721/">publish-testray-report#2721</a><br/></div></div>

2022-08-05 11:38 UTC, Sharryxue commented
Just starting review.

2022-08-05 12:20 UTC, Sharryxue requested changes
Hello @epark18,
Should we add the account role instead of regular role in the test? Since we are more care about whether the account role works as expected or not in this test. I would also turn to Patty for help to confirm if this is expected to add a regular role with Account permission or an account role is better. Thanks.

2022-08-05 12:20 UTC, Sharryxue commented on modules/apps/account/account-test/src/testFunctional/tests/AccountRoles.testcase
> +			JSONUser.setFirstPassword(
Please add the property for this.

2022-08-05 12:20 UTC, Sharryxue commented on modules/apps/account/account-test/src/testFunctional/tests/AccountRoles.testcase
> +		task ("And given that a regular role is created with permissions to assign and view account roles and entries") {
Please nest the And into Given.
And should we create an account role instead of the regular one for this test?

2022-08-08 23:41 UTC, epark18 commented
Thank you for your feedback! Patricia said this one should be Account Roles. Will fix and resend to her.

2022-08-08 23:41 UTC, closed without merging