LPS-169786 | master
Sharryxue/liferay-portal pull request #511
Opened 2022-12-01 08:04 UTC by lilylcl

https://issues.liferay.com/browse/LPS-169786

2022-12-01 08:04 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-12-01 08:04 UTC, lilylcl commented
ci:test:sf

2022-12-01 08:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/5036/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/5036/jenkins-report.html">here</a>.</b></p>

2022-12-01 08:07 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8567ab84e3ba352f600659394a4dee861a74cdaf">8567ab84e3ba352f600659394a4dee861a74cdaf</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/lilylcl/liferay-portal/tree/master-qa-169786">master-qa-169786</a><br/>Branch GIT ID: <a href="https://github.com/lilylcl/liferay-portal/commit/10bf4908b837813105a3c9c42c084688fc00fe86">10bf4908b837813105a3c9c42c084688fc00fe86</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/5036/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/5036/jenkins-report.html">here</a>.</h5></details></html>

2022-12-01 08:08 UTC, lilylcl commented
ci:test:sf

2022-12-01 08:10 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/5036/">test-portal-source-format#5036</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/5036/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/511">Sharryxue#511</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2091909292">[master] ci:test:sf - lilylcl &gt; Sharryxue - PR#511 - 2022-12-01[00:05:08]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/18060/">publish-testray-report#18060</a><br/></div></div>

2022-12-01 08:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/1396/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1396/jenkins-report.html">here</a>.</b></p>

2022-12-01 08:12 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8567ab84e3ba352f600659394a4dee861a74cdaf">8567ab84e3ba352f600659394a4dee861a74cdaf</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/lilylcl/liferay-portal/tree/master-qa-169786">master-qa-169786</a><br/>Branch GIT ID: <a href="https://github.com/lilylcl/liferay-portal/commit/10bf4908b837813105a3c9c42c084688fc00fe86">10bf4908b837813105a3c9c42c084688fc00fe86</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/1396/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1396/jenkins-report.html">here</a>.</h5></details></html>

2022-12-01 08:19 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/1396/">test-portal-source-format#1396</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1396/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/511">Sharryxue#511</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2091909363">[master] ci:test:sf - lilylcl &gt; Sharryxue - PR#511 - 2022-12-01[00:09:20]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/5591/">publish-testray-report#5591</a><br/></div></div>

2022-12-01 12:40 UTC, Sharryxue commented
Just starting review.

2022-12-01 12:42 UTC, Sharryxue requested changes
Hello @lilylcl,
It would be nice to use macro instead of functions here, when you find an exist locator works, please also using the locator to see if there are available macro as well. Thanks in advance.

2022-12-01 12:42 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/macros/User.macro
> +		Click.waitForMenuToggleJSClick(locator1 = "Icon#VERTICAL_ELLIPSIS_BUTTON");
Please use the exist macro instead, you can find it via this locator you used. Thanks in advance.

2022-12-02 02:11 UTC, closed without merging

2022-12-02 02:15 UTC, lilylcl commented
Done and resend https://github.com/Sharryxue/liferay-portal/pull/512, thank you!