LRQA-75988 | master
Sharryxue/liferay-portal pull request #515
Opened 2022-12-02 10:36 UTC by lilylcl

https://issues.liferay.com/browse/LRQA-75988

2022-12-02 10:36 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-12-02 10:36 UTC, lilylcl commented
ci:test:sf

2022-12-02 10:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-source-format/6213/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/6213/jenkins-report.html">here</a>.</b></p>

2022-12-02 10:40 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b69bd6a04fa27629d64448389d92bf7743e4b008">b69bd6a04fa27629d64448389d92bf7743e4b008</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/lilylcl/liferay-portal/tree/master-qa-75988">master-qa-75988</a><br/>Branch GIT ID: <a href="https://github.com/lilylcl/liferay-portal/commit/f48f2d482a6d550c1facba37416a768e3768aa28">f48f2d482a6d550c1facba37416a768e3768aa28</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/6213/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/6213/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found formatting issues:
     [java] The commit 'LRQA-75988 Add reset user password upgrade test for 740/7413' contains the word 'password', which could reveal potential security vulnerablities. Please see the vulnerability keywords that are specified in source-formatter.properties in the liferay-portal repository.
     [java]   at com.liferay.source.formatter.SourceFormatter._validateCommitMessages(SourceFormatter.java:1293)
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:322)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:286)
[stopwatch] [run.batch.test.action: 1:28.103 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:453: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:596: Java returned: 1
      [get] Getting: http://test-1-6/job/test-portal-source-format/6213//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20221202024014528.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20221202024014528.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null314746186.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1253862523
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 412ms
[junitreport] Deleting: /tmp/null1253862523
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 12-02-2022 02:40:20:222 PST</pre></details></html>

2022-12-02 10:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-6.liferay.com/job/test-portal-source-format/6213/">test-portal-source-format#6213</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/6213/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/515">Sharryxue#515</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2095370373">[master] ci:test:sf - lilylcl &gt; Sharryxue - PR#515 - 2022-12-02[02:36:53]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-6.liferay.com/job/publish-testray-report/3416/">publish-testray-report#3416</a><br/></div></div>

2022-12-02 10:51 UTC, lilylcl commented
ci:test:sf

2022-12-02 10:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/3914/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/3914/jenkins-report.html">here</a>.</b></p>

2022-12-02 10:54 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b69bd6a04fa27629d64448389d92bf7743e4b008">b69bd6a04fa27629d64448389d92bf7743e4b008</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/lilylcl/liferay-portal/tree/master-qa-75988">master-qa-75988</a><br/>Branch GIT ID: <a href="https://github.com/lilylcl/liferay-portal/commit/f48f2d482a6d550c1facba37416a768e3768aa28">f48f2d482a6d550c1facba37416a768e3768aa28</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/3914/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/3914/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found formatting issues:
     [java] The commit 'LRQA-75988 Add reset user password upgrade test for 740/7413' contains the word 'password', which could reveal potential security vulnerablities. Please see the vulnerability keywords that are specified in source-formatter.properties in the liferay-portal repository.
     [java]   at com.liferay.source.formatter.SourceFormatter._validateCommitMessages(SourceFormatter.java:1293)
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:322)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:286)
[stopwatch] [run.batch.test.action: 55.238 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:453: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:596: Java returned: 1
      [get] Getting: http://test-1-27/job/test-portal-source-format/3914//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20221202025432699.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20221202025432699.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1668522941.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null811438740
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 137ms
[junitreport] Deleting: /tmp/null811438740
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 12-02-2022 02:54:34:603 PST</pre></details></html>

2022-12-02 11:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/3914/">test-portal-source-format#3914</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/3914/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/515">Sharryxue#515</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2095374219">[master] ci:test:sf - lilylcl &gt; Sharryxue - PR#515 - 2022-12-02[02:51:39]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/14449/">publish-testray-report#14449</a><br/></div></div>

2022-12-05 08:35 UTC, lilylcl commented
ci:test:sf

2022-12-05 08:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/1408/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/1408/jenkins-report.html">here</a>.</b></p>

2022-12-05 08:39 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/201f3d3fec59d2ea77f7773a4ea2a513c779962d">201f3d3fec59d2ea77f7773a4ea2a513c779962d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/lilylcl/liferay-portal/tree/master-qa-75988">master-qa-75988</a><br/>Branch GIT ID: <a href="https://github.com/lilylcl/liferay-portal/commit/ac8796d97ec4f186ce38e94ef8638328e2604a5c">ac8796d97ec4f186ce38e94ef8638328e2604a5c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/1408/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/1408/jenkins-report.html">here</a>.</h5></details></html>

2022-12-05 08:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/1408/">test-portal-source-format#1408</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/1408/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/515">Sharryxue#515</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2101826752">[master] ci:test:sf - lilylcl &gt; Sharryxue - PR#515 - 2022-12-05[00:36:06]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/4721/">publish-testray-report#4721</a><br/></div></div>

2022-12-05 10:17 UTC, lilylcl commented
ci:test:sf

2022-12-05 10:18 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/3295/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/3295/jenkins-report.html">here</a>.</b></p>

2022-12-05 10:20 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/201f3d3fec59d2ea77f7773a4ea2a513c779962d">201f3d3fec59d2ea77f7773a4ea2a513c779962d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/lilylcl/liferay-portal/tree/master-qa-75988">master-qa-75988</a><br/>Branch GIT ID: <a href="https://github.com/lilylcl/liferay-portal/commit/b1042e9a74b599961cddd8cb10a28c84d4eeee93">b1042e9a74b599961cddd8cb10a28c84d4eeee93</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/3295/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/3295/jenkins-report.html">here</a>.</h5></details></html>

2022-12-05 10:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/3295/">test-portal-source-format#3295</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/3295/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/Sharryxue/liferay-portal/pull/515">Sharryxue#515</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2102021153">[master] ci:test:sf - lilylcl &gt; Sharryxue - PR#515 - 2022-12-05[02:17:12]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/11356/">publish-testray-report#11356</a><br/></div></div>

2022-12-06 09:43 UTC, Sharryxue commented
Just starting review.

2022-12-06 09:53 UTC, Sharryxue commented
Need confirm why there is missing version 7413 for one of tests.

2022-12-07 14:56 UTC, Sharryxue requested changes
Hello @lilylcl,
Besides we waiting for a new test added for 74 DXP version, please also refer the comment added, thanks.

2022-12-07 14:56 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/macros/ManagementBar.macro
> +		else {
It would be better to add a description above it to explain why we need this since the function on master was changed. Thanks in advance.

2022-12-08 03:07 UTC, Sharryxue commented on portal-web/test/functional/com/liferay/portalweb/macros/ManagementBar.macro
> +		else {
No need to add the description since this is not a specific macro for DM. Sorry

2022-12-08 03:13 UTC, Sharryxue commented
Just starting review.

2022-12-08 14:24 UTC, Sharryxue commented
No changes needed. :)
Rebase and resend, refer https://github.com/Sharryxue/liferay-portal/pull/524.

2022-12-08 14:24 UTC, closed without merging